import urllib, unicodedata, string
from HTMLParser import HTMLParser

HOME_URL = "http://www.pokepedia.fr"
BASE_URL = "http://www.pokepedia.fr/index.php/Liste_des_Pok%C3%A9mon_par_statistiques_de_base"

def main(pkList, evoList):
    text = ""
    
    for name in pkList:
        evos = []
        for evolutions in evoList:
            if name in evolutions:
                for evo in evolutions:
                    evos.append('PokemonList.perName.get("{}")'.format(evo))
        
        text += '        PokemonList.perName.get("{}").evolutions = new Pokemon[]{{'.format(name) + ','.join(evos) + '};\n'
    
    print text
    
    
    
def buildList():
    resp = urllib.urlopen(BASE_URL)
    p = MainPageParser()
    p.feed(resp.read().decode("utf-8"))
    
    print p.data

def getAttr(attrs, attr):
    for e in attrs:
        if e[0] == attr:
            return e[1]
    return None

class MainPageParser(HTMLParser):
    def __init__(self):
        HTMLParser.__init__(self)
        
        self.inTable = False
        self.inTr = False
        self.inTd = False
        self.inImg = False
        self.inLink = False
        
        self.data = []
    
    def handle_starttag(self, tag, attrs):
        if tag == "table" and getAttr(attrs, "class") == "tableaustandard sortable":
            self.inTable = True
        
        if self.inTable and tag == "tr":
            self.inTr = True
            self.cell = 0
        
        if self.inTr and tag == "td":
            self.inTd = True
            self.cell += 1
            
        if self.inTr and self.cell == 3 and tag == "a":
            self.inLink = True
            
            resp = urllib.urlopen(HOME_URL + getAttr(attrs, "href"))
            p = PokemonParser()
            p.feed(resp.read().decode("utf-8"))
            print p.data
            self.data.append(p.data)
        
    def handle_endtag(self, tag):
        if self.inLink and tag == "a":
            self.inLink = False
        
        if self.inTd and tag == "td":
            self.inTd = False
            
        if self.inTr and tag == "tr":
            self.inTr = False
        
        if tag == "table":
            self.inTable = False
    
    
class PokemonParser(HTMLParser):
    def __init__(self):
        HTMLParser.__init__(self)
        
        self.data = []
        
        self.inH3 = False
        self.getTable = False
        self.inTable = False
        self.row = 0
        self.inTd = False
        self.getContent = False
        self.getContentIfEquals = ""
    
    def handle_starttag(self, tag, attrs):
        if tag == "h3":
            self.inH3 = True
            
            if self.getTable:
                self.getTable = False
        
        if self.inH3 and tag == "span" and getAttr(attrs, "id") == ".C3.89volution":
            self.getTable = True
        
        if self.getTable and tag == "table":
            self.inTable = True
        
        if self.inTable and tag == "tr":
            self.row += 1
        
        if self.inTable and tag == "td":
            self.inTd = True
        
        if self.inTd and tag == "strong":
            self.getContent = True
        
        if self.inTd and tag == "a" and self.row%2 == 0:
            self.getContentIfEquals = getAttr(attrs, "title")
        
    def handle_endtag(self, tag):
        if tag == "a":
            self.getContentIfEquals = ""
        
        if tag == "strong":
            self.getContent = False
        
        if tag == "td":
            self.inTd = False
        
        if tag == "table":
            self.getTable = False
            self.inTable = False
            self.row = 0
        
        if tag == "h3":
            self.inH3 = False
    
    def handle_data(self, data):
        if self.getContent:
            self.data.append(data)
        
        if self.getContentIfEquals and data == self.getContentIfEquals:
            self.data.append(data)
        


#~ [u'Bulbizarre', u'Herbizarre', u'Florizarre', u'Mega-Florizarre']
#~ [u'Bulbizarre', u'Herbizarre', u'Florizarre', u'Mega-Florizarre']
#~ [u'Bulbizarre', u'Herbizarre', u'Florizarre', u'Mega-Florizarre']
#~ [u'Bulbizarre', u'Herbizarre', u'Florizarre', u'Mega-Florizarre']
#~ [u'Salameche', u'Reptincel', u'Dracaufeu', u'Mega-Dracaufeu X', u'Mega-Dracaufeu Y']
#~ [u'Salameche', u'Reptincel', u'Dracaufeu', u'Mega-Dracaufeu X', u'Mega-Dracaufeu Y']
#~ [u'Salameche', u'Reptincel', u'Dracaufeu', u'Mega-Dracaufeu X', u'Mega-Dracaufeu Y']
#~ [u'Salameche', u'Reptincel', u'Dracaufeu', u'Mega-Dracaufeu X', u'Mega-Dracaufeu Y']
#~ [u'Salameche', u'Reptincel', u'Dracaufeu', u'Mega-Dracaufeu X', u'Mega-Dracaufeu Y']
#~ [u'Carapuce', u'Carabaffe', u'Tortank', u'Mega-Tortank']
#~ [u'Carapuce', u'Carabaffe', u'Tortank', u'Mega-Tortank']
#~ [u'Carapuce', u'Carabaffe', u'Tortank', u'Mega-Tortank']
#~ [u'Carapuce', u'Carabaffe', u'Tortank', u'Mega-Tortank']
#~ [u'Chenipan', u'Chrysacier', u'Papilusion']
#~ [u'Chenipan', u'Chrysacier', u'Papilusion']
#~ [u'Chenipan', u'Chrysacier', u'Papilusion']
#~ [u'Aspicot', u'Coconfort', u'Dardargnan']
#~ [u'Aspicot', u'Coconfort', u'Dardargnan']
#~ [u'Aspicot', u'Coconfort', u'Dardargnan']
#~ [u'Roucool', u'Roucoups', u'Roucarnage']
#~ [u'Roucool', u'Roucoups', u'Roucarnage']
#~ [u'Roucool', u'Roucoups', u'Roucarnage']
#~ [u'Rattata', u'Rattatac']
#~ [u'Rattata', u'Rattatac']
#~ [u'Piafabec', u'Rapasdepic']
#~ [u'Piafabec', u'Rapasdepic']
#~ [u'Abo', u'Arbok']
#~ [u'Abo', u'Arbok']
#~ [u'Pichu', u'Pikachu', u'Raichu']
#~ [u'Pichu', u'Pikachu', u'Raichu']
#~ [u'Sabelette', u'Sablaireau']
#~ [u'Sabelette', u'Sablaireau']
#~ [u'Nidoran F', u'Nidorina', u'Nidoqueen']
#~ [u'Nidoran F', u'Nidorina', u'Nidoqueen']
#~ [u'Nidoran F', u'Nidorina', u'Nidoqueen']
#~ [u'Nidoran M', u'Nidorino', u'Nidoking']
#~ [u'Nidoran M', u'Nidorino', u'Nidoking']
#~ [u'Nidoran M', u'Nidorino', u'Nidoking']
#~ [u'Melo', u'Melofee', u'Melodelfe']
#~ [u'Melo', u'Melofee', u'Melodelfe']
#~ [u'Goupix', u'Feunard']
#~ [u'Goupix', u'Feunard']
#~ [u'Toudoudou', u'Rondoudou', u'Grodoudou']
#~ [u'Toudoudou', u'Rondoudou', u'Grodoudou']
#~ [u'Nosferapti', u'Nosferalto', u'Nostenfer']
#~ [u'Nosferapti', u'Nosferalto', u'Nostenfer']
#~ [u'Mystherbe', u'Ortide', u'Rafflesia', u'Joliflor']
#~ [u'Mystherbe', u'Ortide', u'Rafflesia', u'Joliflor']
#~ [u'Mystherbe', u'Ortide', u'Rafflesia', u'Joliflor']
#~ [u'Paras', u'Parasect']
#~ [u'Paras', u'Parasect']
#~ [u'Mimitoss', u'Aeromite']
#~ [u'Mimitoss', u'Aeromite']
#~ [u'Taupiqueur', u'Triopikeur']
#~ [u'Taupiqueur', u'Triopikeur']
#~ [u'Miaouss', u'Persian']
#~ [u'Miaouss', u'Persian']
#~ [u'Psykokwak', u'Akwakwak']
#~ [u'Psykokwak', u'Akwakwak']
#~ [u'Ferosinge', u'Colossinge']
#~ [u'Ferosinge', u'Colossinge']
#~ [u'Caninos', u'Arcanin']
#~ [u'Caninos', u'Arcanin']
#~ [u'Ptitard', u'Tetarte', u'Tartard', u'Tarpaud']
#~ [u'Ptitard', u'Tetarte', u'Tartard', u'Tarpaud']
#~ [u'Ptitard', u'Tetarte', u'Tartard', u'Tarpaud']
#~ [u'Abra', u'Kadabra', u'Alakazam', u'Mega-Alakazam']
#~ [u'Abra', u'Kadabra', u'Alakazam', u'Mega-Alakazam']
#~ [u'Abra', u'Kadabra', u'Alakazam', u'Mega-Alakazam']
#~ [u'Abra', u'Kadabra', u'Alakazam', u'Mega-Alakazam']
#~ [u'Machoc', u'Machopeur', u'Mackogneur']
#~ [u'Machoc', u'Machopeur', u'Mackogneur']
#~ [u'Machoc', u'Machopeur', u'Mackogneur']
#~ [u'Chetiflor', u'Boustiflor', u'Empiflor']
#~ [u'Chetiflor', u'Boustiflor', u'Empiflor']
#~ [u'Chetiflor', u'Boustiflor', u'Empiflor']
#~ [u'Tentacool', u'Tentacruel']
#~ [u'Tentacool', u'Tentacruel']
#~ [u'Racaillou', u'Gravalanch', u'Grolem']
#~ [u'Racaillou', u'Gravalanch', u'Grolem']
#~ [u'Racaillou', u'Gravalanch', u'Grolem']
#~ [u'Ponyta', u'Galopa']
#~ [u'Ponyta', u'Galopa']
#~ [u'Ramoloss', u'Flagadoss', u'Roigada']
#~ [u'Ramoloss', u'Flagadoss', u'Roigada']
#~ [u'Magneti', u'Magneton', u'Magnezone']
#~ [u'Magneti', u'Magneton', u'Magnezone']
#~ []
#~ [u'Doduo', u'Dodrio']
#~ [u'Doduo', u'Dodrio']
#~ [u'Otaria', u'Lamantine']
#~ [u'Otaria', u'Lamantine']
#~ [u'Tadmorv', u'Grotadmorv']
#~ [u'Tadmorv', u'Grotadmorv']
#~ [u'Kokiyas', u'Crustabri']
#~ [u'Kokiyas', u'Crustabri']
#~ [u'Fantominus', u'Spectrum', u'Ectoplasma', u'Mega-Ectoplasma']
#~ [u'Fantominus', u'Spectrum', u'Ectoplasma', u'Mega-Ectoplasma']
#~ [u'Fantominus', u'Spectrum', u'Ectoplasma', u'Mega-Ectoplasma']
#~ [u'Fantominus', u'Spectrum', u'Ectoplasma', u'Mega-Ectoplasma']
#~ [u'Onix', u'Steelix']
#~ [u'Soporifik', u'Hypnomade']
#~ [u'Soporifik', u'Hypnomade']
#~ [u'Krabby', u'Krabboss']
#~ [u'Krabby', u'Krabboss']
#~ [u'Voltorbe', u'Electrode']
#~ [u'Voltorbe', u'Electrode']
#~ [u'Noeunoeuf', u'Noadkoko']
#~ [u'Noeunoeuf', u'Noadkoko']
#~ [u'Osselait', u'Ossatueur']
#~ [u'Osselait', u'Ossatueur']
#~ [u'Debugant', u'Kicklee', u'Tygnon', u'Kapoera']
#~ [u'Debugant', u'Kicklee', u'Tygnon', u'Kapoera']
#~ [u'Excelangue', u'Coudlangue']
#~ [u'Smogo', u'Smogogo']
#~ [u'Smogo', u'Smogogo']
#~ [u'Rhinocorne', u'Rhinoferos', u'Rhinastoc']
#~ [u'Rhinocorne', u'Rhinoferos', u'Rhinastoc']
#~ [u'Ptiravi', u'Leveinard', u'Leuphorie']
#~ [u'Saquedeneu', u'Bouldeneu']
#~ [u'Kangourex', u'Mega-Kangourex']
#~ [u'Kangourex', u'Mega-Kangourex']
#~ [u'Hypotrempe', u'Hypocean', u'Hyporoi']
#~ [u'Hypotrempe', u'Hypocean', u'Hyporoi']
#~ [u'Poissirene', u'Poissoroy']
#~ [u'Poissirene', u'Poissoroy']
#~ []
#~ []
#~ [u'Mime Jr.', u'M. Mime']
#~ [u'Insecateur', u'Cizayox', u'Mega-Cizayox']
#~ [u'Lippouti', u'Lippoutou']
#~ [u'Elekid', u'Elektek', u'Elekable']
#~ [u'Magby', u'Magmar', u'Maganon']
#~ [u'Scarabrute', u'Mega-Scarabrute']
#~ [u'Scarabrute', u'Mega-Scarabrute']
#~ []
#~ [u'Magicarpe', u'Leviator', u'Mega-Leviator']
#~ [u'Magicarpe', u'Leviator', u'Mega-Leviator']
#~ [u'Magicarpe', u'Leviator', u'Mega-Leviator']
#~ []
#~ []
#~ [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali']
#~ [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali']
#~ [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali']
#~ [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali']
#~ [u'Porygon', u'Porygon2', u'Porygon-Z']
#~ [u'Amonita', u'Amonistar']
#~ [u'Amonita', u'Amonistar']
#~ [u'Kabuto', u'Kabutops']
#~ [u'Kabuto', u'Kabutops']
#~ [u'Ptera', u'Mega-Ptera']
#~ [u'Goinfrex', u'Ronflex']
#~ []
#~ []
#~ []
#~ [u'Minidraco', u'Draco', u'Dracolosse']
#~ [u'Minidraco', u'Draco', u'Dracolosse']
#~ [u'Minidraco', u'Draco', u'Dracolosse']
#~ [u'Mewtwo', u'Mega-Mewtwo X', u'Mega-Mewtwo Y']
#~ [u'Mewtwo', u'Mega-Mewtwo X', u'Mega-Mewtwo Y']
#~ [u'Mewtwo', u'Mega-Mewtwo X', u'Mega-Mewtwo Y']
#~ []
#~ [u'Germignon', u'Macronium', u'Meganium']
#~ [u'Germignon', u'Macronium', u'Meganium']
#~ [u'Germignon', u'Macronium', u'Meganium']
#~ [u'Hericendre', u'Feurisson', u'Typhlosion']
#~ [u'Hericendre', u'Feurisson', u'Typhlosion']
#~ [u'Hericendre', u'Feurisson', u'Typhlosion']
#~ [u'Kaiminus', u'Crocrodil', u'Aligatueur']
#~ [u'Kaiminus', u'Crocrodil', u'Aligatueur']
#~ [u'Kaiminus', u'Crocrodil', u'Aligatueur']
#~ [u'Fouinette', u'Fouinar']
#~ [u'Fouinette', u'Fouinar']
#~ [u'Hoot-hoot', u'Noarfang']
#~ [u'Hoot-hoot', u'Noarfang']
#~ [u'Coxy', u'Coxyclaque']
#~ [u'Coxy', u'Coxyclaque']
#~ [u'Mimigal', u'Migalos']
#~ [u'Mimigal', u'Migalos']
#~ [u'Nosferapti', u'Nosferalto', u'Nostenfer']
#~ [u'Loupio', u'Lanturn']
#~ [u'Loupio', u'Lanturn']
#~ [u'Pichu', u'Pikachu', u'Raichu']
#~ [u'Melo', u'Melofee', u'Melodelfe']
#~ [u'Toudoudou', u'Rondoudou', u'Grodoudou']
#~ [u'Togepi', u'Togetic', u'Togekiss']
#~ [u'Togepi', u'Togetic', u'Togekiss']
#~ [u'Natu', u'Xatu']
#~ [u'Natu', u'Xatu']
#~ [u'Wattouat', u'Lainergie', u'Pharamp', u'Mega-Pharamp']
#~ [u'Wattouat', u'Lainergie', u'Pharamp', u'Mega-Pharamp']
#~ [u'Wattouat', u'Lainergie', u'Pharamp', u'Mega-Pharamp']
#~ [u'Wattouat', u'Lainergie', u'Pharamp', u'Mega-Pharamp']
#~ [u'Mystherbe', u'Ortide', u'Rafflesia', u'Joliflor']
#~ [u'Azurill', u'Marill', u'Azumarill']
#~ [u'Azurill', u'Marill', u'Azumarill']
#~ [u'Manzai', u'Simularbre']
#~ [u'Ptitard', u'Tetarte', u'Tartard', u'Tarpaud']
#~ [u'Granivol', u'Floravol', u'Cotovol']
#~ [u'Granivol', u'Floravol', u'Cotovol']
#~ [u'Granivol', u'Floravol', u'Cotovol']
#~ [u'Capumain', u'Capidextre']
#~ [u'Tournegrin', u'Heliatronc']
#~ [u'Tournegrin', u'Heliatronc']
#~ [u'Yanma', u'Yanmega']
#~ [u'Axoloto', u'Maraiste']
#~ [u'Axoloto', u'Maraiste']
#~ [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali']
#~ [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali']
#~ [u'Cornebre', u'Corboss']
#~ [u'Ramoloss', u'Flagadoss', u'Roigada']
#~ [u'Feuforeve', u'Magireve']
#~ []
#~ [u'Okeoke', u'Qulbutoke']
#~ []
#~ [u'Pomdepik', u'Foretress']
#~ [u'Pomdepik', u'Foretress']
#~ []
#~ [u'Scorplane', u'Scorvol']
#~ [u'Onix', u'Steelix']
#~ [u'Snubbull', u'Granbull']
#~ [u'Snubbull', u'Granbull']
#~ []
#~ [u'Insecateur', u'Cizayox', u'Mega-Cizayox']
#~ [u'Insecateur', u'Cizayox', u'Mega-Cizayox']
#~ []
#~ [u'Scarhino', u'Mega-Scarhino']
#~ [u'Scarhino', u'Mega-Scarhino']
#~ [u'Farfuret', u'Dimoret']
#~ [u'Teddiursa', u'Ursaring']
#~ [u'Teddiursa', u'Ursaring']
#~ [u'Limagma', u'Volcaropod']
#~ [u'Limagma', u'Volcaropod']
#~ [u'Marcacrin', u'Cochignon', u'Mammochon']
#~ [u'Marcacrin', u'Cochignon', u'Mammochon']
#~ []
#~ [u'Remoraid', u'Octillery']
#~ [u'Remoraid', u'Octillery']
#~ []
#~ [u'Babimanta', u'Demanta']
#~ []
#~ [u'Malosse', u'Demolosse', u'Mega-Demolosse']
#~ [u'Malosse', u'Demolosse', u'Mega-Demolosse']
#~ [u'Malosse', u'Demolosse', u'Mega-Demolosse']
#~ [u'Hypotrempe', u'Hypocean', u'Hyporoi']
#~ [u'Phanpy', u'Donphan']
#~ [u'Phanpy', u'Donphan']
#~ [u'Porygon', u'Porygon2', u'Porygon-Z']
#~ []
#~ []
#~ [u'Debugant', u'Kicklee', u'Tygnon', u'Kapoera']
#~ [u'Debugant', u'Kicklee', u'Tygnon', u'Kapoera']
#~ [u'Lippouti', u'Lippoutou']
#~ [u'Elekid', u'Elektek', u'Elekable']
#~ [u'Magby', u'Magmar', u'Maganon']
#~ []
#~ [u'Ptiravi', u'Leveinard', u'Leuphorie']
#~ []
#~ []
#~ []
#~ [u'Embrylex', u'Ymphect', u'Tyranocif', u'Mega-Tyranocif']
#~ [u'Embrylex', u'Ymphect', u'Tyranocif', u'Mega-Tyranocif']
#~ [u'Embrylex', u'Ymphect', u'Tyranocif', u'Mega-Tyranocif']
#~ [u'Embrylex', u'Ymphect', u'Tyranocif', u'Mega-Tyranocif']
#~ []
#~ []
#~ []
#~ [u'Arcko', u'Massko', u'Jungko']
#~ [u'Arcko', u'Massko', u'Jungko']
#~ [u'Arcko', u'Massko', u'Jungko']
#~ [u'Poussifeu', u'Galifeu', u'Brasegali', u'Mega-Brasegali']
#~ [u'Poussifeu', u'Galifeu', u'Brasegali', u'Mega-Brasegali']
#~ [u'Poussifeu', u'Galifeu', u'Brasegali', u'Mega-Brasegali']
#~ [u'Poussifeu', u'Galifeu', u'Brasegali', u'Mega-Brasegali']
#~ [u'Gobou', u'Flobio', u'Laggron']
#~ [u'Gobou', u'Flobio', u'Laggron']
#~ [u'Gobou', u'Flobio', u'Laggron']
#~ [u'Medhyena', u'Grahyena']
#~ [u'Medhyena', u'Grahyena']
#~ [u'Zigzaton', u'Lineon']
#~ [u'Zigzaton', u'Lineon']
#~ [u'Chenipotte', u'Armulys', u'Blindalys', u'Charmillon', u'Papinox']
#~ [u'Chenipotte', u'Armulys', u'Blindalys', u'Charmillon', u'Papinox']
#~ [u'Chenipotte', u'Armulys', u'Blindalys', u'Charmillon', u'Papinox']
#~ [u'Chenipotte', u'Armulys', u'Blindalys', u'Charmillon', u'Papinox']
#~ [u'Chenipotte', u'Armulys', u'Blindalys', u'Charmillon', u'Papinox']
#~ [u'Nenupiot', u'Lombre', u'Ludicolo']
#~ [u'Nenupiot', u'Lombre', u'Ludicolo']
#~ [u'Nenupiot', u'Lombre', u'Ludicolo']
#~ [u'Grainipiot', u'Pifeuil', u'Tengalice']
#~ [u'Grainipiot', u'Pifeuil', u'Tengalice']
#~ [u'Grainipiot', u'Pifeuil', u'Tengalice']
#~ [u'Nirondelle', u'Heledelle']
#~ [u'Nirondelle', u'Heledelle']
#~ [u'Goelise', u'Bekipan']
#~ [u'Goelise', u'Bekipan']
#~ [u'Tarsal', u'Kirlia', u'Gardevoir', u'Gallame', u'Mega-Gardevoir']
#~ [u'Tarsal', u'Kirlia', u'Gardevoir', u'Gallame', u'Mega-Gardevoir']
#~ [u'Tarsal', u'Kirlia', u'Gardevoir', u'Gallame', u'Mega-Gardevoir']
#~ [u'Tarsal', u'Kirlia', u'Gardevoir', u'Gallame', u'Mega-Gardevoir']
#~ [u'Arakdo', u'Maskadra']
#~ [u'Arakdo', u'Maskadra']
#~ [u'Balignon', u'Chapignon']
#~ [u'Balignon', u'Chapignon']
#~ [u'Parecool', u'Vigoroth', u'Monaflemit']
#~ [u'Parecool', u'Vigoroth', u'Monaflemit']
#~ [u'Parecool', u'Vigoroth', u'Monaflemit']
#~ [u'Ningale', u'Ninjask', u'Munja']
#~ [u'Ningale', u'Ninjask', u'Munja']
#~ [u'Ningale', u'Ninjask', u'Munja']
#~ [u'Chuchmur', u'Ramboum', u'Brouhabam']
#~ [u'Chuchmur', u'Ramboum', u'Brouhabam']
#~ [u'Chuchmur', u'Ramboum', u'Brouhabam']
#~ [u'Makuhita', u'Hariyama']
#~ [u'Makuhita', u'Hariyama']
#~ [u'Azurill', u'Marill', u'Azumarill']
#~ [u'Tarinor', u'Tarinorme']
#~ [u'Skitty', u'Delcatty']
#~ [u'Skitty', u'Delcatty']
#~ []
#~ [u'Mysdibule', u'Mega-Mysdibule']
#~ [u'Mysdibule', u'Mega-Mysdibule']
#~ [u'Galekid', u'Galegon', u'Galeking', u'Mega-Galeking']
#~ [u'Galekid', u'Galegon', u'Galeking', u'Mega-Galeking']
#~ [u'Galekid', u'Galegon', u'Galeking', u'Mega-Galeking']
#~ [u'Galekid', u'Galegon', u'Galeking', u'Mega-Galeking']
#~ [u'Meditikka', u'Charmina', u'Mega-Charmina']
#~ [u'Meditikka', u'Charmina', u'Mega-Charmina']
#~ [u'Meditikka', u'Charmina', u'Mega-Charmina']
#~ [u'Dynavolt', u'Elecsprint', u'Mega-Elecsprint']
#~ [u'Dynavolt', u'Elecsprint', u'Mega-Elecsprint']
#~ [u'Dynavolt', u'Elecsprint', u'Mega-Elecsprint']
#~ []
#~ []
#~ []
#~ []
#~ [u'Rozbouton', u'Roselia', u'Roserade']
#~ [u'Gloupti', u'Avaltout']
#~ [u'Gloupti', u'Avaltout']
#~ [u'Carvanha', u'Sharpedo']
#~ [u'Carvanha', u'Sharpedo']
#~ [u'Wailmer', u'Wailord']
#~ [u'Wailmer', u'Wailord']
#~ [u'Chamallot', u'Camerupt']
#~ [u'Chamallot', u'Camerupt']
#~ []
#~ [u'Spoink', u'Groret']
#~ [u'Spoink', u'Groret']
#~ []
#~ [u'Kraknoix', u'Vibraninf', u'Libegon']
#~ [u'Kraknoix', u'Vibraninf', u'Libegon']
#~ [u'Kraknoix', u'Vibraninf', u'Libegon']
#~ [u'Cacnea', u'Cacturne']
#~ [u'Cacnea', u'Cacturne']
#~ [u'Tylton', u'Altaria']
#~ [u'Tylton', u'Altaria']
#~ []
#~ []
#~ []
#~ []
#~ [u'Barloche', u'Barbicha']
#~ [u'Barloche', u'Barbicha']
#~ [u'Ecrapince', u'Colhomard']
#~ [u'Ecrapince', u'Colhomard']
#~ [u'Balbuto', u'Kaorine']
#~ [u'Balbuto', u'Kaorine']
#~ [u'Lilia', u'Vacilys']
#~ [u'Lilia', u'Vacilys']
#~ [u'Anorith', u'Armaldo']
#~ [u'Anorith', u'Armaldo']
#~ [u'Barpau', u'Milobellus']
#~ [u'Barpau', u'Milobellus']
#~ []
#~ []
#~ [u'Polichombr', u'Branette', u'Mega-Branette']
#~ [u'Polichombr', u'Branette', u'Mega-Branette']
#~ [u'Polichombr', u'Branette', u'Mega-Branette']
#~ [u'Skelenox', u'Teraclope', u'Noctunoir']
#~ [u'Skelenox', u'Teraclope', u'Noctunoir']
#~ []
#~ [u'Korillon', u'Eoko']
#~ [u'Absol', u'Mega-Absol']
#~ [u'Absol', u'Mega-Absol']
#~ [u'Okeoke', u'Qulbutoke']
#~ [u'Stalgamin', u'Oniglali', u'Momartik']
#~ [u'Stalgamin', u'Oniglali', u'Momartik']
#~ [u'Obalie', u'Phogleur', u'Kaimorse']
#~ [u'Obalie', u'Phogleur', u'Kaimorse']
#~ [u'Obalie', u'Phogleur', u'Kaimorse']
#~ [u'Coquiperl', u'Serpang', u'Rosabyss']
#~ [u'Coquiperl', u'Serpang', u'Rosabyss']
#~ [u'Coquiperl', u'Serpang', u'Rosabyss']
#~ []
#~ []
#~ [u'Draby', u'Drackhaus', u'Drattak']
#~ [u'Draby', u'Drackhaus', u'Drattak']
#~ [u'Draby', u'Drackhaus', u'Drattak']
#~ [u'Terhal', u'Metang', u'Metalosse']
#~ [u'Terhal', u'Metang', u'Metalosse']
#~ [u'Terhal', u'Metang', u'Metalosse']
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ [u'Tortipouss', u'Boskara', u'Torterra']
#~ [u'Tortipouss', u'Boskara', u'Torterra']
#~ [u'Tortipouss', u'Boskara', u'Torterra']
#~ [u'Ouisticram', u'Chimpenfeu', u'Simiabraz']
#~ [u'Ouisticram', u'Chimpenfeu', u'Simiabraz']
#~ [u'Ouisticram', u'Chimpenfeu', u'Simiabraz']
#~ [u'Tiplouf', u'Prinplouf', u'Pingoleon']
#~ [u'Tiplouf', u'Prinplouf', u'Pingoleon']
#~ [u'Tiplouf', u'Prinplouf', u'Pingoleon']
#~ [u'Etourmi', u'Etourvol', u'Etouraptor']
#~ [u'Etourmi', u'Etourvol', u'Etouraptor']
#~ [u'Etourmi', u'Etourvol', u'Etouraptor']
#~ [u'Keunotor', u'Castorno']
#~ [u'Keunotor', u'Castorno']
#~ [u'Crikzik', u'Melokrik']
#~ [u'Crikzik', u'Melokrik']
#~ [u'Lixy', u'Luxio', u'Luxray']
#~ [u'Lixy', u'Luxio', u'Luxray']
#~ [u'Lixy', u'Luxio', u'Luxray']
#~ [u'Rozbouton', u'Roselia', u'Roserade']
#~ [u'Rozbouton', u'Roselia', u'Roserade']
#~ [u'Kranidos', u'Charkos']
#~ [u'Kranidos', u'Charkos']
#~ [u'Dinoclier', u'Bastiodon']
#~ [u'Dinoclier', u'Bastiodon']
#~ [u'Cheniti', u'Cheniselle', u'Papilord']
#~ [u'Cheniti', u'Cheniselle', u'Papilord']
#~ [u'Cheniti', u'Cheniselle', u'Papilord']
#~ [u'Cheniti', u'Cheniselle', u'Papilord']
#~ [u'Cheniti', u'Cheniselle', u'Papilord']
#~ [u'Apitrini', u'Apireine']
#~ [u'Apitrini', u'Apireine']
#~ []
#~ [u'Mustebouee', u'Musteflott']
#~ [u'Mustebouee', u'Musteflott']
#~ [u'Ceribou', u'Ceriflor']
#~ [u'Ceribou', u'Ceriflor']
#~ [u'Sancoki', u'Tritosor']
#~ [u'Sancoki', u'Tritosor']
#~ [u'Capumain', u'Capidextre']
#~ [u'Baudrive', u'Grodrive']
#~ [u'Baudrive', u'Grodrive']
#~ [u'Laporeille', u'Lockpin']
#~ [u'Laporeille', u'Lockpin']
#~ [u'Feuforeve', u'Magireve']
#~ [u'Cornebre', u'Corboss']
#~ [u'Chaglam', u'Chaffreux']
#~ [u'Chaglam', u'Chaffreux']
#~ [u'Korillon', u'Eoko']
#~ [u'Moufouette', u'Moufflair']
#~ [u'Moufouette', u'Moufflair']
#~ [u'Archeomire', u'Archeodong']
#~ [u'Archeomire', u'Archeodong']
#~ [u'Manzai', u'Simularbre']
#~ [u'Mime Jr.', u'M. Mime']
#~ [u'Ptiravi', u'Leveinard', u'Leuphorie']
#~ []
#~ []
#~ [u'Griknot', u'Carmache', u'Carchacrok', u'Mega-Carchacrok']
#~ [u'Griknot', u'Carmache', u'Carchacrok', u'Mega-Carchacrok']
#~ [u'Griknot', u'Carmache', u'Carchacrok', u'Mega-Carchacrok']
#~ [u'Griknot', u'Carmache', u'Carchacrok', u'Mega-Carchacrok']
#~ [u'Goinfrex', u'Ronflex']
#~ [u'Riolu', u'Lucario', u'Mega-Lucario']
#~ [u'Riolu', u'Lucario', u'Mega-Lucario']
#~ [u'Riolu', u'Lucario', u'Mega-Lucario']
#~ [u'Hippopotas', u'Hippodocus']
#~ [u'Hippopotas', u'Hippodocus']
#~ [u'Rapion', u'Drascore']
#~ [u'Rapion', u'Drascore']
#~ [u'Cradopaud', u'Coatox']
#~ [u'Cradopaud', u'Coatox']
#~ []
#~ [u'Ecayon', u'Lumineon']
#~ [u'Ecayon', u'Lumineon']
#~ [u'Babimanta', u'Demanta']
#~ [u'Blizzi', u'Blizzaroi', u'Mega-Blizzaroi']
#~ [u'Blizzi', u'Blizzaroi', u'Mega-Blizzaroi']
#~ [u'Blizzi', u'Blizzaroi', u'Mega-Blizzaroi']
#~ [u'Farfuret', u'Dimoret']
#~ [u'Magneti', u'Magneton', u'Magnezone']
#~ [u'Excelangue', u'Coudlangue']
#~ [u'Rhinocorne', u'Rhinoferos', u'Rhinastoc']
#~ [u'Saquedeneu', u'Bouldeneu']
#~ [u'Elekid', u'Elektek', u'Elekable']
#~ [u'Magby', u'Magmar', u'Maganon']
#~ [u'Togepi', u'Togetic', u'Togekiss']
#~ [u'Yanma', u'Yanmega']
#~ [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali']
#~ [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali']
#~ [u'Scorplane', u'Scorvol']
#~ [u'Marcacrin', u'Cochignon', u'Mammochon']
#~ [u'Porygon', u'Porygon2', u'Porygon-Z']
#~ [u'Tarsal', u'Kirlia', u'Gardevoir', u'Gallame', u'Mega-Gardevoir']
#~ [u'Tarinor', u'Tarinorme']
#~ [u'Skelenox', u'Teraclope', u'Noctunoir']
#~ [u'Stalgamin', u'Oniglali', u'Momartik']
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ [u'Vipelierre', u'Lianaja', u'Majaspic']
#~ [u'Vipelierre', u'Lianaja', u'Majaspic']
#~ [u'Vipelierre', u'Lianaja', u'Majaspic']
#~ [u'Gruikui', u'Grotichon', u'Roitiflam']
#~ [u'Gruikui', u'Grotichon', u'Roitiflam']
#~ [u'Gruikui', u'Grotichon', u'Roitiflam']
#~ [u'Moustillon', u'Mateloutre', u'Clamiral']
#~ [u'Moustillon', u'Mateloutre', u'Clamiral']
#~ [u'Moustillon', u'Mateloutre', u'Clamiral']
#~ [u'Ratentif', u'Miradar']
#~ [u'Ratentif', u'Miradar']
#~ [u'Ponchiot', u'Ponchien', u'Mastouffe']
#~ [u'Ponchiot', u'Ponchien', u'Mastouffe']
#~ [u'Ponchiot', u'Ponchien', u'Mastouffe']
#~ [u'Chacripan', u'Leopardus']
#~ [u'Chacripan', u'Leopardus']
#~ [u'Feuillajou', u'Feuiloutan']
#~ [u'Feuillajou', u'Feuiloutan']
#~ [u'Flamajou', u'Flamoutan']
#~ [u'Flamajou', u'Flamoutan']
#~ [u'Flotajou', u'Flotoutan']
#~ [u'Flotajou', u'Flotoutan']
#~ [u'Munna', u'Mushana']
#~ [u'Munna', u'Mushana']
#~ [u'Poichigeon', u'Colombeau', u'Deflaisan']
#~ [u'Poichigeon', u'Colombeau', u'Deflaisan']
#~ [u'Poichigeon', u'Colombeau', u'Deflaisan']
#~ [u'Zebibron', u'Zeblitz']
#~ [u'Zebibron', u'Zeblitz']
#~ [u'Nodulithe', u'Geolithe', u'Gigalithe']
#~ [u'Nodulithe', u'Geolithe', u'Gigalithe']
#~ [u'Nodulithe', u'Geolithe', u'Gigalithe']
#~ [u'Chovsourir', u'Rhinolove']
#~ [u'Chovsourir', u'Rhinolove']
#~ [u'Rototaupe', u'Minotaupe']
#~ [u'Rototaupe', u'Minotaupe']
#~ []
#~ [u'Charpenti', u'Ouvrifier', u'Betochef']
#~ [u'Charpenti', u'Ouvrifier', u'Betochef']
#~ [u'Charpenti', u'Ouvrifier', u'Betochef']
#~ [u'Tritonde', u'Batracne', u'Crapustule']
#~ [u'Tritonde', u'Batracne', u'Crapustule']
#~ [u'Tritonde', u'Batracne', u'Crapustule']
#~ []
#~ []
#~ [u'Larveyette', u'Couverdure', u'Manternel']
#~ [u'Larveyette', u'Couverdure', u'Manternel']
#~ [u'Larveyette', u'Couverdure', u'Manternel']
#~ [u'Venipatte', u'Scobolide', u'Brutapode']
#~ [u'Venipatte', u'Scobolide', u'Brutapode']
#~ [u'Venipatte', u'Scobolide', u'Brutapode']
#~ [u'Doudouvet', u'Farfaduvet']
#~ [u'Doudouvet', u'Farfaduvet']
#~ [u'Chlorobule', u'Fragilady']
#~ [u'Chlorobule', u'Fragilady']
#~ []
#~ [u'Mascaiman', u'Escroco', u'Crocorible']
#~ [u'Mascaiman', u'Escroco', u'Crocorible']
#~ [u'Mascaiman', u'Escroco', u'Crocorible']
#~ [u'Darumarond', u'Darumacho']
#~ [u'Darumarond', u'Darumacho']
#~ [u'Darumarond', u'Darumacho']
#~ []
#~ [u'Crabicoque', u'Crabaraque']
#~ [u'Crabicoque', u'Crabaraque']
#~ [u'Baggiguane', u'Baggaid']
#~ [u'Baggiguane', u'Baggaid']
#~ []
#~ [u'Tutafeh', u'Tutankafer']
#~ [u'Tutafeh', u'Tutankafer']
#~ [u'Carapagos', u'Megapagos']
#~ [u'Carapagos', u'Megapagos']
#~ [u'Arkeapti', u'Aeropteryx']
#~ [u'Arkeapti', u'Aeropteryx']
#~ [u'Miamiasme', u'Miasmax']
#~ [u'Miamiasme', u'Miasmax']
#~ [u'Zorua', u'Zoroark']
#~ [u'Zorua', u'Zoroark']
#~ [u'Chinchidou', u'Pashmilla']
#~ [u'Chinchidou', u'Pashmilla']
#~ [u'Scrutella', u'Mesmerella', u'Siderella']
#~ [u'Scrutella', u'Mesmerella', u'Siderella']
#~ [u'Scrutella', u'Mesmerella', u'Siderella']
#~ [u'Nucleos', u'Meios']
#~ [u'Nucleos', u'Meios']
#~ [u'Nucleos', u'Meios', u'Symbios200e']
#~ [u'Couaneton', u'Lakmecygne']
#~ [u'Couaneton', u'Lakmecygne']
#~ [u'Sorbebe', u'Sorboul', u'Sorbouboul']
#~ [u'Sorbebe', u'Sorboul', u'Sorbouboul']
#~ [u'Sorbebe', u'Sorboul', u'Sorbouboul']
#~ [u'Vivaldaim', u'Haydaim']
#~ [u'Vivaldaim', u'Haydaim']
#~ []
#~ [u'Carabing', u'Lancargot']
#~ [u'Carabing', u'Lancargot']
#~ [u'Trompignon', u'Gaulet']
#~ [u'Trompignon', u'Gaulet']
#~ [u'Viskuse', u'Moyade']
#~ [u'Viskuse', u'Moyade']
#~ []
#~ [u'Statitik', u'Mygavolt']
#~ [u'Statitik', u'Mygavolt']
#~ [u'Grindur', u'Noacier']
#~ [u'Grindur', u'Noacier']
#~ [u'Tic', u'Clic', u'Cliticlic']
#~ [u'Tic', u'Clic', u'Cliticlic']
#~ [u'Tic', u'Clic', u'Cliticlic']
#~ [u'Anchwatt', u'Lamperoie', u'Ohmassacre']
#~ [u'Anchwatt', u'Lamperoie', u'Ohmassacre']
#~ [u'Anchwatt', u'Lamperoie', u'Ohmassacre']
#~ [u'Lewsor', u'Neitram']
#~ [u'Lewsor', u'Neitram']
#~ [u'Funecire', u'Melancolux', u'Lugulabre']
#~ [u'Funecire', u'Melancolux', u'Lugulabre']
#~ [u'Funecire', u'Melancolux', u'Lugulabre']
#~ [u'Coupenotte', u'Incisache', u'Tranchodon']
#~ [u'Coupenotte', u'Incisache', u'Tranchodon']
#~ [u'Coupenotte', u'Incisache', u'Tranchodon']
#~ [u'Polarhume', u'Polagriffe']
#~ [u'Polarhume', u'Polagriffe']
#~ []
#~ [u'Escargaume', u'Limaspeed']
#~ [u'Escargaume', u'Limaspeed']
#~ []
#~ [u'Kungfouine', u'Shaofouine']
#~ [u'Kungfouine', u'Shaofouine']
#~ []
#~ [u'Gringolem', u'Golemastoc']
#~ [u'Gringolem', u'Golemastoc']
#~ [u'Scalpion', u'Scalproie']
#~ [u'Scalpion', u'Scalproie']
#~ []
#~ [u'Furaiglon', u'Gueriaigle']
#~ [u'Furaiglon', u'Gueriaigle']
#~ [u'Vostourno', u'Vaututrice']
#~ [u'Vostourno', u'Vaututrice']
#~ []
#~ []
#~ [u'Solochi', u'Diamat', u'Trioxhydre']
#~ [u'Solochi', u'Diamat', u'Trioxhydre']
#~ [u'Solochi', u'Diamat', u'Trioxhydre']
#~ [u'Pyronille', u'Pyrax']
#~ [u'Pyronille', u'Pyrax']
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ []
#~ [u'Marisson', u'Boguerisse', u'Blindepique']
#~ [u'Marisson', u'Boguerisse', u'Blindepique']
#~ [u'Marisson', u'Boguerisse', u'Blindepique']
#~ [u'Feunnec', u'Roussil', u'Goupelin']
#~ [u'Feunnec', u'Roussil', u'Goupelin']
#~ [u'Feunnec', u'Roussil', u'Goupelin']
#~ [u'Grenousse', u'Croaporal', u'Amphinobi']
#~ [u'Grenousse', u'Croaporal', u'Amphinobi']
#~ [u'Grenousse', u'Croaporal', u'Amphinobi']
#~ [u'Sapereau', u'Excavarenne']
#~ [u'Sapereau', u'Excavarenne']
#~ [u'Passerouge', u'Braisillon', u'Flambusard']
#~ [u'Passerouge', u'Braisillon', u'Flambusard']
#~ [u'Passerouge', u'Braisillon', u'Flambusard']
#~ [u'Lepidonille', u'Peregrain', u'Prismillon']
#~ [u'Lepidonille', u'Peregrain', u'Prismillon']
#~ [u'Lepidonille', u'Peregrain', u'Prismillon']
#~ [u'Helionceau', u'Nemelios']
#~ [u'Helionceau', u'Nemelios']
#~ [u'Flabebe', u'Floette', u'Florges']
#~ [u'Flabebe', u'Floette', u'Florges']
#~ [u'Flabebe', u'Floette', u'Florges']
#~ [u'Cabriolaine', u'Chevroum']
#~ [u'Cabriolaine', u'Chevroum']
#~ [u'Pandespiegle', u'Pandarbare']
#~ [u'Pandespiegle', u'Pandarbare']
#~ []
#~ [u'Psystigri', u'Mistigrix']
#~ [u'Psystigri', u'Mistigrix']
#~ [u'Monorpale', u'Dimocles', u'Exagide']
#~ [u'Monorpale', u'Dimocles', u'Exagide']
#~ [u'Monorpale', u'Dimocles', u'Exagide']
#~ [u'Monorpale', u'Dimocles', u'Exagide']
#~ [u'Fluvetin', u'Cocotine']
#~ [u'Fluvetin', u'Cocotine']
#~ [u'Sucroquin', u'Cupcanaille']
#~ [u'Sucroquin', u'Cupcanaille']
#~ [u'Sepiatop', u'Sepiatroce']
#~ [u'Sepiatop', u'Sepiatroce']
#~ [u'Opermine', u'Golgopathe']
#~ [u'Opermine', u'Golgopathe']
#~ [u'Venalgue', u'Kravarech']
#~ [u'Venalgue', u'Kravarech']
#~ [u'Flingouste', u'Gamblast']
#~ [u'Flingouste', u'Gamblast']
#~ [u'Galvaran', u'Iguolta']
#~ [u'Galvaran', u'Iguolta']
#~ [u'Ptyranidur', u'Rexillius']
#~ [u'Ptyranidur', u'Rexillius']
#~ [u'Amagara', u'Dragmara']
#~ [u'Amagara', u'Dragmara']
#~ [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali']
#~ []
#~ []
#~ []
#~ [u'Mucuscule', u'Colimucus', u'Muplodocus']
#~ [u'Mucuscule', u'Colimucus', u'Muplodocus']
#~ [u'Mucuscule', u'Colimucus', u'Muplodocus']
#~ []
#~ [u'Brocelome', u'Desseliande']
#~ [u'Brocelome', u'Desseliande']
#~ [u'Pitrouille', u'Banshitrouye']
#~ [u'Pitrouille', u'Banshitrouye']
#~ [u'Pitrouille', u'Banshitrouye']
#~ [u'Pitrouille', u'Banshitrouye']
#~ [u'Pitrouille', u'Banshitrouye']
#~ [u'Pitrouille', u'Banshitrouye']
#~ [u'Pitrouille', u'Banshitrouye']
#~ [u'Pitrouille', u'Banshitrouye']
#~ [u'Grelacon', u'Seracrawl']
#~ [u'Grelacon', u'Seracrawl']
#~ [u'Sonistrelle', u'Bruyverne']
#~ [u'Sonistrelle', u'Bruyverne']
#~ []
#~ []
#~ []
#~ list = [[u'Bulbizarre', u'Herbizarre', u'Florizarre', u'Mega-Florizarre'], [u'Bulbizarre', u'Herbizarre', u'Florizarre', u'Mega-Florizarre'], [u'Bulbizarre', u'Herbizarre', u'Florizarre', u'Mega-Florizarre'], [u'Bulbizarre', u'Herbizarre', u'Florizarre', u'Mega-Florizarre'], [u'Salameche', u'Reptincel', u'Dracaufeu', u'Mega-Dracaufeu X', u'Mega-Dracaufeu Y'], [u'Salameche', u'Reptincel', u'Dracaufeu', u'Mega-Dracaufeu X', u'Mega-Dracaufeu Y'], [u'Salameche', u'Reptincel', u'Dracaufeu', u'Mega-Dracaufeu X', u'Mega-Dracaufeu Y'], [u'Salameche', u'Reptincel', u'Dracaufeu', u'Mega-Dracaufeu X', u'Mega-Dracaufeu Y'], [u'Salameche', u'Reptincel', u'Dracaufeu', u'Mega-Dracaufeu X', u'Mega-Dracaufeu Y'], [u'Carapuce', u'Carabaffe', u'Tortank', u'Mega-Tortank'], [u'Carapuce', u'Carabaffe', u'Tortank', u'Mega-Tortank'], [u'Carapuce', u'Carabaffe', u'Tortank', u'Mega-Tortank'], [u'Carapuce', u'Carabaffe', u'Tortank', u'Mega-Tortank'], [u'Chenipan', u'Chrysacier', u'Papilusion'], [u'Chenipan', u'Chrysacier', u'Papilusion'], [u'Chenipan', u'Chrysacier', u'Papilusion'], [u'Aspicot', u'Coconfort', u'Dardargnan'], [u'Aspicot', u'Coconfort', u'Dardargnan'], [u'Aspicot', u'Coconfort', u'Dardargnan'], [u'Roucool', u'Roucoups', u'Roucarnage'], [u'Roucool', u'Roucoups', u'Roucarnage'], [u'Roucool', u'Roucoups', u'Roucarnage'], [u'Rattata', u'Rattatac'], [u'Rattata', u'Rattatac'], [u'Piafabec', u'Rapasdepic'], [u'Piafabec', u'Rapasdepic'], [u'Abo', u'Arbok'], [u'Abo', u'Arbok'], [u'Pichu', u'Pikachu', u'Raichu'], [u'Pichu', u'Pikachu', u'Raichu'], [u'Sabelette', u'Sablaireau'], [u'Sabelette', u'Sablaireau'], [u'Nidoran F', u'Nidorina', u'Nidoqueen'], [u'Nidoran F', u'Nidorina', u'Nidoqueen'], [u'Nidoran F', u'Nidorina', u'Nidoqueen'], [u'Nidoran M', u'Nidorino', u'Nidoking'], [u'Nidoran M', u'Nidorino', u'Nidoking'], [u'Nidoran M', u'Nidorino', u'Nidoking'], [u'Melo', u'Melofee', u'Melodelfe'], [u'Melo', u'Melofee', u'Melodelfe'], [u'Goupix', u'Feunard'], [u'Goupix', u'Feunard'], [u'Toudoudou', u'Rondoudou', u'Grodoudou'], [u'Toudoudou', u'Rondoudou', u'Grodoudou'], [u'Nosferapti', u'Nosferalto', u'Nostenfer'], [u'Nosferapti', u'Nosferalto', u'Nostenfer'], [u'Mystherbe', u'Ortide', u'Rafflesia', u'Joliflor'], [u'Mystherbe', u'Ortide', u'Rafflesia', u'Joliflor'], [u'Mystherbe', u'Ortide', u'Rafflesia', u'Joliflor'], [u'Paras', u'Parasect'], [u'Paras', u'Parasect'], [u'Mimitoss', u'Aeromite'], [u'Mimitoss', u'Aeromite'], [u'Taupiqueur', u'Triopikeur'], [u'Taupiqueur', u'Triopikeur'], [u'Miaouss', u'Persian'], [u'Miaouss', u'Persian'], [u'Psykokwak', u'Akwakwak'], [u'Psykokwak', u'Akwakwak'], [u'Ferosinge', u'Colossinge'], [u'Ferosinge', u'Colossinge'], [u'Caninos', u'Arcanin'], [u'Caninos', u'Arcanin'], [u'Ptitard', u'Tetarte', u'Tartard', u'Tarpaud'], [u'Ptitard', u'Tetarte', u'Tartard', u'Tarpaud'], [u'Ptitard', u'Tetarte', u'Tartard', u'Tarpaud'], [u'Abra', u'Kadabra', u'Alakazam', u'Mega-Alakazam'], [u'Abra', u'Kadabra', u'Alakazam', u'Mega-Alakazam'], [u'Abra', u'Kadabra', u'Alakazam', u'Mega-Alakazam'], [u'Abra', u'Kadabra', u'Alakazam', u'Mega-Alakazam'], [u'Machoc', u'Machopeur', u'Mackogneur'], [u'Machoc', u'Machopeur', u'Mackogneur'], [u'Machoc', u'Machopeur', u'Mackogneur'], [u'Chetiflor', u'Boustiflor', u'Empiflor'], [u'Chetiflor', u'Boustiflor', u'Empiflor'], [u'Chetiflor', u'Boustiflor', u'Empiflor'], [u'Tentacool', u'Tentacruel'], [u'Tentacool', u'Tentacruel'], [u'Racaillou', u'Gravalanch', u'Grolem'], [u'Racaillou', u'Gravalanch', u'Grolem'], [u'Racaillou', u'Gravalanch', u'Grolem'], [u'Ponyta', u'Galopa'], [u'Ponyta', u'Galopa'], [u'Ramoloss', u'Flagadoss', u'Roigada'], [u'Ramoloss', u'Flagadoss', u'Roigada'], [u'Magneti', u'Magneton', u'Magnezone'], [u'Magneti', u'Magneton', u'Magnezone'], [], [u'Doduo', u'Dodrio'], [u'Doduo', u'Dodrio'], [u'Otaria', u'Lamantine'], [u'Otaria', u'Lamantine'], [u'Tadmorv', u'Grotadmorv'], [u'Tadmorv', u'Grotadmorv'], [u'Kokiyas', u'Crustabri'], [u'Kokiyas', u'Crustabri'], [u'Fantominus', u'Spectrum', u'Ectoplasma', u'Mega-Ectoplasma'], [u'Fantominus', u'Spectrum', u'Ectoplasma', u'Mega-Ectoplasma'], [u'Fantominus', u'Spectrum', u'Ectoplasma', u'Mega-Ectoplasma'], [u'Fantominus', u'Spectrum', u'Ectoplasma', u'Mega-Ectoplasma'], [u'Onix', u'Steelix'], [u'Soporifik', u'Hypnomade'], [u'Soporifik', u'Hypnomade'], [u'Krabby', u'Krabboss'], [u'Krabby', u'Krabboss'], [u'Voltorbe', u'Electrode'], [u'Voltorbe', u'Electrode'], [u'Noeunoeuf', u'Noadkoko'], [u'Noeunoeuf', u'Noadkoko'], [u'Osselait', u'Ossatueur'], [u'Osselait', u'Ossatueur'], [u'Debugant', u'Kicklee', u'Tygnon', u'Kapoera'], [u'Debugant', u'Kicklee', u'Tygnon', u'Kapoera'], [u'Excelangue', u'Coudlangue'], [u'Smogo', u'Smogogo'], [u'Smogo', u'Smogogo'], [u'Rhinocorne', u'Rhinoferos', u'Rhinastoc'], [u'Rhinocorne', u'Rhinoferos', u'Rhinastoc'], [u'Ptiravi', u'Leveinard', u'Leuphorie'], [u'Saquedeneu', u'Bouldeneu'], [u'Kangourex', u'Mega-Kangourex'], [u'Kangourex', u'Mega-Kangourex'], [u'Hypotrempe', u'Hypocean', u'Hyporoi'], [u'Hypotrempe', u'Hypocean', u'Hyporoi'], [u'Poissirene', u'Poissoroy'], [u'Poissirene', u'Poissoroy'], [], [], [u'Mime Jr.', u'M. Mime'], [u'Insecateur', u'Cizayox', u'Mega-Cizayox'], [u'Lippouti', u'Lippoutou'], [u'Elekid', u'Elektek', u'Elekable'], [u'Magby', u'Magmar', u'Maganon'], [u'Scarabrute', u'Mega-Scarabrute'], [u'Scarabrute', u'Mega-Scarabrute'], [], [u'Magicarpe', u'Leviator', u'Mega-Leviator'], [u'Magicarpe', u'Leviator', u'Mega-Leviator'], [u'Magicarpe', u'Leviator', u'Mega-Leviator'], [], [], [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali'], [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali'], [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali'], [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali'], [u'Porygon', u'Porygon2', u'Porygon-Z'], [u'Amonita', u'Amonistar'], [u'Amonita', u'Amonistar'], [u'Kabuto', u'Kabutops'], [u'Kabuto', u'Kabutops'], [u'Ptera', u'Mega-Ptera'], [u'Goinfrex', u'Ronflex'], [], [], [], [u'Minidraco', u'Draco', u'Dracolosse'], [u'Minidraco', u'Draco', u'Dracolosse'], [u'Minidraco', u'Draco', u'Dracolosse'], [u'Mewtwo', u'Mega-Mewtwo X', u'Mega-Mewtwo Y'], [u'Mewtwo', u'Mega-Mewtwo X', u'Mega-Mewtwo Y'], [u'Mewtwo', u'Mega-Mewtwo X', u'Mega-Mewtwo Y'], [], [u'Germignon', u'Macronium', u'Meganium'], [u'Germignon', u'Macronium', u'Meganium'], [u'Germignon', u'Macronium', u'Meganium'], [u'Hericendre', u'Feurisson', u'Typhlosion'], [u'Hericendre', u'Feurisson', u'Typhlosion'], [u'Hericendre', u'Feurisson', u'Typhlosion'], [u'Kaiminus', u'Crocrodil', u'Aligatueur'], [u'Kaiminus', u'Crocrodil', u'Aligatueur'], [u'Kaiminus', u'Crocrodil', u'Aligatueur'], [u'Fouinette', u'Fouinar'], [u'Fouinette', u'Fouinar'], [u'Hoot-hoot', u'Noarfang'], [u'Hoot-hoot', u'Noarfang'], [u'Coxy', u'Coxyclaque'], [u'Coxy', u'Coxyclaque'], [u'Mimigal', u'Migalos'], [u'Mimigal', u'Migalos'], [u'Nosferapti', u'Nosferalto', u'Nostenfer'], [u'Loupio', u'Lanturn'], [u'Loupio', u'Lanturn'], [u'Pichu', u'Pikachu', u'Raichu'], [u'Melo', u'Melofee', u'Melodelfe'], [u'Toudoudou', u'Rondoudou', u'Grodoudou'], [u'Togepi', u'Togetic', u'Togekiss'], [u'Togepi', u'Togetic', u'Togekiss'], [u'Natu', u'Xatu'], [u'Natu', u'Xatu'], [u'Wattouat', u'Lainergie', u'Pharamp', u'Mega-Pharamp'], [u'Wattouat', u'Lainergie', u'Pharamp', u'Mega-Pharamp'], [u'Wattouat', u'Lainergie', u'Pharamp', u'Mega-Pharamp'], [u'Wattouat', u'Lainergie', u'Pharamp', u'Mega-Pharamp'], [u'Mystherbe', u'Ortide', u'Rafflesia', u'Joliflor'], [u'Azurill', u'Marill', u'Azumarill'], [u'Azurill', u'Marill', u'Azumarill'], [u'Manzai', u'Simularbre'], [u'Ptitard', u'Tetarte', u'Tartard', u'Tarpaud'], [u'Granivol', u'Floravol', u'Cotovol'], [u'Granivol', u'Floravol', u'Cotovol'], [u'Granivol', u'Floravol', u'Cotovol'], [u'Capumain', u'Capidextre'], [u'Tournegrin', u'Heliatronc'], [u'Tournegrin', u'Heliatronc'], [u'Yanma', u'Yanmega'], [u'Axoloto', u'Maraiste'], [u'Axoloto', u'Maraiste'], [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali'], [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali'], [u'Cornebre', u'Corboss'], [u'Ramoloss', u'Flagadoss', u'Roigada'], [u'Feuforeve', u'Magireve'], [], [u'Okeoke', u'Qulbutoke'], [], [u'Pomdepik', u'Foretress'], [u'Pomdepik', u'Foretress'], [], [u'Scorplane', u'Scorvol'], [u'Onix', u'Steelix'], [u'Snubbull', u'Granbull'], [u'Snubbull', u'Granbull'], [], [u'Insecateur', u'Cizayox', u'Mega-Cizayox'], [u'Insecateur', u'Cizayox', u'Mega-Cizayox'], [], [u'Scarhino', u'Mega-Scarhino'], [u'Scarhino', u'Mega-Scarhino'], [u'Farfuret', u'Dimoret'], [u'Teddiursa', u'Ursaring'], [u'Teddiursa', u'Ursaring'], [u'Limagma', u'Volcaropod'], [u'Limagma', u'Volcaropod'], [u'Marcacrin', u'Cochignon', u'Mammochon'], [u'Marcacrin', u'Cochignon', u'Mammochon'], [], [u'Remoraid', u'Octillery'], [u'Remoraid', u'Octillery'], [], [u'Babimanta', u'Demanta'], [], [u'Malosse', u'Demolosse', u'Mega-Demolosse'], [u'Malosse', u'Demolosse', u'Mega-Demolosse'], [u'Malosse', u'Demolosse', u'Mega-Demolosse'], [u'Hypotrempe', u'Hypocean', u'Hyporoi'], [u'Phanpy', u'Donphan'], [u'Phanpy', u'Donphan'], [u'Porygon', u'Porygon2', u'Porygon-Z'], [], [], [u'Debugant', u'Kicklee', u'Tygnon', u'Kapoera'], [u'Debugant', u'Kicklee', u'Tygnon', u'Kapoera'], [u'Lippouti', u'Lippoutou'], [u'Elekid', u'Elektek', u'Elekable'], [u'Magby', u'Magmar', u'Maganon'], [], [u'Ptiravi', u'Leveinard', u'Leuphorie'], [], [], [], [u'Embrylex', u'Ymphect', u'Tyranocif', u'Mega-Tyranocif'], [u'Embrylex', u'Ymphect', u'Tyranocif', u'Mega-Tyranocif'], [u'Embrylex', u'Ymphect', u'Tyranocif', u'Mega-Tyranocif'], [u'Embrylex', u'Ymphect', u'Tyranocif', u'Mega-Tyranocif'], [], [], [], [u'Arcko', u'Massko', u'Jungko'], [u'Arcko', u'Massko', u'Jungko'], [u'Arcko', u'Massko', u'Jungko'], [u'Poussifeu', u'Galifeu', u'Brasegali', u'Mega-Brasegali'], [u'Poussifeu', u'Galifeu', u'Brasegali', u'Mega-Brasegali'], [u'Poussifeu', u'Galifeu', u'Brasegali', u'Mega-Brasegali'], [u'Poussifeu', u'Galifeu', u'Brasegali', u'Mega-Brasegali'], [u'Gobou', u'Flobio', u'Laggron'], [u'Gobou', u'Flobio', u'Laggron'], [u'Gobou', u'Flobio', u'Laggron'], [u'Medhyena', u'Grahyena'], [u'Medhyena', u'Grahyena'], [u'Zigzaton', u'Lineon'], [u'Zigzaton', u'Lineon'], [u'Chenipotte', u'Armulys', u'Blindalys', u'Charmillon', u'Papinox'], [u'Chenipotte', u'Armulys', u'Blindalys', u'Charmillon', u'Papinox'], [u'Chenipotte', u'Armulys', u'Blindalys', u'Charmillon', u'Papinox'], [u'Chenipotte', u'Armulys', u'Blindalys', u'Charmillon', u'Papinox'], [u'Chenipotte', u'Armulys', u'Blindalys', u'Charmillon', u'Papinox'], [u'Nenupiot', u'Lombre', u'Ludicolo'], [u'Nenupiot', u'Lombre', u'Ludicolo'], [u'Nenupiot', u'Lombre', u'Ludicolo'], [u'Grainipiot', u'Pifeuil', u'Tengalice'], [u'Grainipiot', u'Pifeuil', u'Tengalice'], [u'Grainipiot', u'Pifeuil', u'Tengalice'], [u'Nirondelle', u'Heledelle'], [u'Nirondelle', u'Heledelle'], [u'Goelise', u'Bekipan'], [u'Goelise', u'Bekipan'], [u'Tarsal', u'Kirlia', u'Gardevoir', u'Gallame', u'Mega-Gardevoir'], [u'Tarsal', u'Kirlia', u'Gardevoir', u'Gallame', u'Mega-Gardevoir'], [u'Tarsal', u'Kirlia', u'Gardevoir', u'Gallame', u'Mega-Gardevoir'], [u'Tarsal', u'Kirlia', u'Gardevoir', u'Gallame', u'Mega-Gardevoir'], [u'Arakdo', u'Maskadra'], [u'Arakdo', u'Maskadra'], [u'Balignon', u'Chapignon'], [u'Balignon', u'Chapignon'], [u'Parecool', u'Vigoroth', u'Monaflemit'], [u'Parecool', u'Vigoroth', u'Monaflemit'], [u'Parecool', u'Vigoroth', u'Monaflemit'], [u'Ningale', u'Ninjask', u'Munja'], [u'Ningale', u'Ninjask', u'Munja'], [u'Ningale', u'Ninjask', u'Munja'], [u'Chuchmur', u'Ramboum', u'Brouhabam'], [u'Chuchmur', u'Ramboum', u'Brouhabam'], [u'Chuchmur', u'Ramboum', u'Brouhabam'], [u'Makuhita', u'Hariyama'], [u'Makuhita', u'Hariyama'], [u'Azurill', u'Marill', u'Azumarill'], [u'Tarinor', u'Tarinorme'], [u'Skitty', u'Delcatty'], [u'Skitty', u'Delcatty'], [], [u'Mysdibule', u'Mega-Mysdibule'], [u'Mysdibule', u'Mega-Mysdibule'], [u'Galekid', u'Galegon', u'Galeking', u'Mega-Galeking'], [u'Galekid', u'Galegon', u'Galeking', u'Mega-Galeking'], [u'Galekid', u'Galegon', u'Galeking', u'Mega-Galeking'], [u'Galekid', u'Galegon', u'Galeking', u'Mega-Galeking'], [u'Meditikka', u'Charmina', u'Mega-Charmina'], [u'Meditikka', u'Charmina', u'Mega-Charmina'], [u'Meditikka', u'Charmina', u'Mega-Charmina'], [u'Dynavolt', u'Elecsprint', u'Mega-Elecsprint'], [u'Dynavolt', u'Elecsprint', u'Mega-Elecsprint'], [u'Dynavolt', u'Elecsprint', u'Mega-Elecsprint'], [], [], [], [], [u'Rozbouton', u'Roselia', u'Roserade'], [u'Gloupti', u'Avaltout'], [u'Gloupti', u'Avaltout'], [u'Carvanha', u'Sharpedo'], [u'Carvanha', u'Sharpedo'], [u'Wailmer', u'Wailord'], [u'Wailmer', u'Wailord'], [u'Chamallot', u'Camerupt'], [u'Chamallot', u'Camerupt'], [], [u'Spoink', u'Groret'], [u'Spoink', u'Groret'], [], [u'Kraknoix', u'Vibraninf', u'Libegon'], [u'Kraknoix', u'Vibraninf', u'Libegon'], [u'Kraknoix', u'Vibraninf', u'Libegon'], [u'Cacnea', u'Cacturne'], [u'Cacnea', u'Cacturne'], [u'Tylton', u'Altaria'], [u'Tylton', u'Altaria'], [], [], [], [], [u'Barloche', u'Barbicha'], [u'Barloche', u'Barbicha'], [u'Ecrapince', u'Colhomard'], [u'Ecrapince', u'Colhomard'], [u'Balbuto', u'Kaorine'], [u'Balbuto', u'Kaorine'], [u'Lilia', u'Vacilys'], [u'Lilia', u'Vacilys'], [u'Anorith', u'Armaldo'], [u'Anorith', u'Armaldo'], [u'Barpau', u'Milobellus'], [u'Barpau', u'Milobellus'], [], [], [u'Polichombr', u'Branette', u'Mega-Branette'], [u'Polichombr', u'Branette', u'Mega-Branette'], [u'Polichombr', u'Branette', u'Mega-Branette'], [u'Skelenox', u'Teraclope', u'Noctunoir'], [u'Skelenox', u'Teraclope', u'Noctunoir'], [], [u'Korillon', u'Eoko'], [u'Absol', u'Mega-Absol'], [u'Absol', u'Mega-Absol'], [u'Okeoke', u'Qulbutoke'], [u'Stalgamin', u'Oniglali', u'Momartik'], [u'Stalgamin', u'Oniglali', u'Momartik'], [u'Obalie', u'Phogleur', u'Kaimorse'], [u'Obalie', u'Phogleur', u'Kaimorse'], [u'Obalie', u'Phogleur', u'Kaimorse'], [u'Coquiperl', u'Serpang', u'Rosabyss'], [u'Coquiperl', u'Serpang', u'Rosabyss'], [u'Coquiperl', u'Serpang', u'Rosabyss'], [], [], [u'Draby', u'Drackhaus', u'Drattak'], [u'Draby', u'Drackhaus', u'Drattak'], [u'Draby', u'Drackhaus', u'Drattak'], [u'Terhal', u'Metang', u'Metalosse'], [u'Terhal', u'Metang', u'Metalosse'], [u'Terhal', u'Metang', u'Metalosse'], [], [], [], [], [], [], [], [], [], [], [], [], [], [u'Tortipouss', u'Boskara', u'Torterra'], [u'Tortipouss', u'Boskara', u'Torterra'], [u'Tortipouss', u'Boskara', u'Torterra'], [u'Ouisticram', u'Chimpenfeu', u'Simiabraz'], [u'Ouisticram', u'Chimpenfeu', u'Simiabraz'], [u'Ouisticram', u'Chimpenfeu', u'Simiabraz'], [u'Tiplouf', u'Prinplouf', u'Pingoleon'], [u'Tiplouf', u'Prinplouf', u'Pingoleon'], [u'Tiplouf', u'Prinplouf', u'Pingoleon'], [u'Etourmi', u'Etourvol', u'Etouraptor'], [u'Etourmi', u'Etourvol', u'Etouraptor'], [u'Etourmi', u'Etourvol', u'Etouraptor'], [u'Keunotor', u'Castorno'], [u'Keunotor', u'Castorno'], [u'Crikzik', u'Melokrik'], [u'Crikzik', u'Melokrik'], [u'Lixy', u'Luxio', u'Luxray'], [u'Lixy', u'Luxio', u'Luxray'], [u'Lixy', u'Luxio', u'Luxray'], [u'Rozbouton', u'Roselia', u'Roserade'], [u'Rozbouton', u'Roselia', u'Roserade'], [u'Kranidos', u'Charkos'], [u'Kranidos', u'Charkos'], [u'Dinoclier', u'Bastiodon'], [u'Dinoclier', u'Bastiodon'], [u'Cheniti', u'Cheniselle', u'Papilord'], [u'Cheniti', u'Cheniselle', u'Papilord'], [u'Cheniti', u'Cheniselle', u'Papilord'], [u'Cheniti', u'Cheniselle', u'Papilord'], [u'Cheniti', u'Cheniselle', u'Papilord'], [u'Apitrini', u'Apireine'], [u'Apitrini', u'Apireine'], [], [u'Mustebouee', u'Musteflott'], [u'Mustebouee', u'Musteflott'], [u'Ceribou', u'Ceriflor'], [u'Ceribou', u'Ceriflor'], [u'Sancoki', u'Tritosor'], [u'Sancoki', u'Tritosor'], [u'Capumain', u'Capidextre'], [u'Baudrive', u'Grodrive'], [u'Baudrive', u'Grodrive'], [u'Laporeille', u'Lockpin'], [u'Laporeille', u'Lockpin'], [u'Feuforeve', u'Magireve'], [u'Cornebre', u'Corboss'], [u'Chaglam', u'Chaffreux'], [u'Chaglam', u'Chaffreux'], [u'Korillon', u'Eoko'], [u'Moufouette', u'Moufflair'], [u'Moufouette', u'Moufflair'], [u'Archeomire', u'Archeodong'], [u'Archeomire', u'Archeodong'], [u'Manzai', u'Simularbre'], [u'Mime Jr.', u'M. Mime'], [u'Ptiravi', u'Leveinard', u'Leuphorie'], [], [], [u'Griknot', u'Carmache', u'Carchacrok', u'Mega-Carchacrok'], [u'Griknot', u'Carmache', u'Carchacrok', u'Mega-Carchacrok'], [u'Griknot', u'Carmache', u'Carchacrok', u'Mega-Carchacrok'], [u'Griknot', u'Carmache', u'Carchacrok', u'Mega-Carchacrok'], [u'Goinfrex', u'Ronflex'], [u'Riolu', u'Lucario', u'Mega-Lucario'], [u'Riolu', u'Lucario', u'Mega-Lucario'], [u'Riolu', u'Lucario', u'Mega-Lucario'], [u'Hippopotas', u'Hippodocus'], [u'Hippopotas', u'Hippodocus'], [u'Rapion', u'Drascore'], [u'Rapion', u'Drascore'], [u'Cradopaud', u'Coatox'], [u'Cradopaud', u'Coatox'], [], [u'Ecayon', u'Lumineon'], [u'Ecayon', u'Lumineon'], [u'Babimanta', u'Demanta'], [u'Blizzi', u'Blizzaroi', u'Mega-Blizzaroi'], [u'Blizzi', u'Blizzaroi', u'Mega-Blizzaroi'], [u'Blizzi', u'Blizzaroi', u'Mega-Blizzaroi'], [u'Farfuret', u'Dimoret'], [u'Magneti', u'Magneton', u'Magnezone'], [u'Excelangue', u'Coudlangue'], [u'Rhinocorne', u'Rhinoferos', u'Rhinastoc'], [u'Saquedeneu', u'Bouldeneu'], [u'Elekid', u'Elektek', u'Elekable'], [u'Magby', u'Magmar', u'Maganon'], [u'Togepi', u'Togetic', u'Togekiss'], [u'Yanma', u'Yanmega'], [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali'], [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali'], [u'Scorplane', u'Scorvol'], [u'Marcacrin', u'Cochignon', u'Mammochon'], [u'Porygon', u'Porygon2', u'Porygon-Z'], [u'Tarsal', u'Kirlia', u'Gardevoir', u'Gallame', u'Mega-Gardevoir'], [u'Tarinor', u'Tarinorme'], [u'Skelenox', u'Teraclope', u'Noctunoir'], [u'Stalgamin', u'Oniglali', u'Momartik'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [u'Vipelierre', u'Lianaja', u'Majaspic'], [u'Vipelierre', u'Lianaja', u'Majaspic'], [u'Vipelierre', u'Lianaja', u'Majaspic'], [u'Gruikui', u'Grotichon', u'Roitiflam'], [u'Gruikui', u'Grotichon', u'Roitiflam'], [u'Gruikui', u'Grotichon', u'Roitiflam'], [u'Moustillon', u'Mateloutre', u'Clamiral'], [u'Moustillon', u'Mateloutre', u'Clamiral'], [u'Moustillon', u'Mateloutre', u'Clamiral'], [u'Ratentif', u'Miradar'], [u'Ratentif', u'Miradar'], [u'Ponchiot', u'Ponchien', u'Mastouffe'], [u'Ponchiot', u'Ponchien', u'Mastouffe'], [u'Ponchiot', u'Ponchien', u'Mastouffe'], [u'Chacripan', u'Leopardus'], [u'Chacripan', u'Leopardus'], [u'Feuillajou', u'Feuiloutan'], [u'Feuillajou', u'Feuiloutan'], [u'Flamajou', u'Flamoutan'], [u'Flamajou', u'Flamoutan'], [u'Flotajou', u'Flotoutan'], [u'Flotajou', u'Flotoutan'], [u'Munna', u'Mushana'], [u'Munna', u'Mushana'], [u'Poichigeon', u'Colombeau', u'Deflaisan'], [u'Poichigeon', u'Colombeau', u'Deflaisan'], [u'Poichigeon', u'Colombeau', u'Deflaisan'], [u'Zebibron', u'Zeblitz'], [u'Zebibron', u'Zeblitz'], [u'Nodulithe', u'Geolithe', u'Gigalithe'], [u'Nodulithe', u'Geolithe', u'Gigalithe'], [u'Nodulithe', u'Geolithe', u'Gigalithe'], [u'Chovsourir', u'Rhinolove'], [u'Chovsourir', u'Rhinolove'], [u'Rototaupe', u'Minotaupe'], [u'Rototaupe', u'Minotaupe'], [], [u'Charpenti', u'Ouvrifier', u'Betochef'], [u'Charpenti', u'Ouvrifier', u'Betochef'], [u'Charpenti', u'Ouvrifier', u'Betochef'], [u'Tritonde', u'Batracne', u'Crapustule'], [u'Tritonde', u'Batracne', u'Crapustule'], [u'Tritonde', u'Batracne', u'Crapustule'], [], [], [u'Larveyette', u'Couverdure', u'Manternel'], [u'Larveyette', u'Couverdure', u'Manternel'], [u'Larveyette', u'Couverdure', u'Manternel'], [u'Venipatte', u'Scobolide', u'Brutapode'], [u'Venipatte', u'Scobolide', u'Brutapode'], [u'Venipatte', u'Scobolide', u'Brutapode'], [u'Doudouvet', u'Farfaduvet'], [u'Doudouvet', u'Farfaduvet'], [u'Chlorobule', u'Fragilady'], [u'Chlorobule', u'Fragilady'], [], [u'Mascaiman', u'Escroco', u'Crocorible'], [u'Mascaiman', u'Escroco', u'Crocorible'], [u'Mascaiman', u'Escroco', u'Crocorible'], [u'Darumarond', u'Darumacho'], [u'Darumarond', u'Darumacho'], [u'Darumarond', u'Darumacho'], [], [u'Crabicoque', u'Crabaraque'], [u'Crabicoque', u'Crabaraque'], [u'Baggiguane', u'Baggaid'], [u'Baggiguane', u'Baggaid'], [], [u'Tutafeh', u'Tutankafer'], [u'Tutafeh', u'Tutankafer'], [u'Carapagos', u'Megapagos'], [u'Carapagos', u'Megapagos'], [u'Arkeapti', u'Aeropteryx'], [u'Arkeapti', u'Aeropteryx'], [u'Miamiasme', u'Miasmax'], [u'Miamiasme', u'Miasmax'], [u'Zorua', u'Zoroark'], [u'Zorua', u'Zoroark'], [u'Chinchidou', u'Pashmilla'], [u'Chinchidou', u'Pashmilla'], [u'Scrutella', u'Mesmerella', u'Siderella'], [u'Scrutella', u'Mesmerella', u'Siderella'], [u'Scrutella', u'Mesmerella', u'Siderella'], [u'Nucleos', u'Meios'], [u'Nucleos', u'Meios'], [u'Nucleos', u'Meios', u'Symbios200e'], [u'Couaneton', u'Lakmecygne'], [u'Couaneton', u'Lakmecygne'], [u'Sorbebe', u'Sorboul', u'Sorbouboul'], [u'Sorbebe', u'Sorboul', u'Sorbouboul'], [u'Sorbebe', u'Sorboul', u'Sorbouboul'], [u'Vivaldaim', u'Haydaim'], [u'Vivaldaim', u'Haydaim'], [], [u'Carabing', u'Lancargot'], [u'Carabing', u'Lancargot'], [u'Trompignon', u'Gaulet'], [u'Trompignon', u'Gaulet'], [u'Viskuse', u'Moyade'], [u'Viskuse', u'Moyade'], [], [u'Statitik', u'Mygavolt'], [u'Statitik', u'Mygavolt'], [u'Grindur', u'Noacier'], [u'Grindur', u'Noacier'], [u'Tic', u'Clic', u'Cliticlic'], [u'Tic', u'Clic', u'Cliticlic'], [u'Tic', u'Clic', u'Cliticlic'], [u'Anchwatt', u'Lamperoie', u'Ohmassacre'], [u'Anchwatt', u'Lamperoie', u'Ohmassacre'], [u'Anchwatt', u'Lamperoie', u'Ohmassacre'], [u'Lewsor', u'Neitram'], [u'Lewsor', u'Neitram'], [u'Funecire', u'Melancolux', u'Lugulabre'], [u'Funecire', u'Melancolux', u'Lugulabre'], [u'Funecire', u'Melancolux', u'Lugulabre'], [u'Coupenotte', u'Incisache', u'Tranchodon'], [u'Coupenotte', u'Incisache', u'Tranchodon'], [u'Coupenotte', u'Incisache', u'Tranchodon'], [u'Polarhume', u'Polagriffe'], [u'Polarhume', u'Polagriffe'], [], [u'Escargaume', u'Limaspeed'], [u'Escargaume', u'Limaspeed'], [], [u'Kungfouine', u'Shaofouine'], [u'Kungfouine', u'Shaofouine'], [], [u'Gringolem', u'Golemastoc'], [u'Gringolem', u'Golemastoc'], [u'Scalpion', u'Scalproie'], [u'Scalpion', u'Scalproie'], [], [u'Furaiglon', u'Gueriaigle'], [u'Furaiglon', u'Gueriaigle'], [u'Vostourno', u'Vaututrice'], [u'Vostourno', u'Vaututrice'], [], [], [u'Solochi', u'Diamat', u'Trioxhydre'], [u'Solochi', u'Diamat', u'Trioxhydre'], [u'Solochi', u'Diamat', u'Trioxhydre'], [u'Pyronille', u'Pyrax'], [u'Pyronille', u'Pyrax'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [u'Marisson', u'Boguerisse', u'Blindepique'], [u'Marisson', u'Boguerisse', u'Blindepique'], [u'Marisson', u'Boguerisse', u'Blindepique'], [u'Feunnec', u'Roussil', u'Goupelin'], [u'Feunnec', u'Roussil', u'Goupelin'], [u'Feunnec', u'Roussil', u'Goupelin'], [u'Grenousse', u'Croaporal', u'Amphinobi'], [u'Grenousse', u'Croaporal', u'Amphinobi'], [u'Grenousse', u'Croaporal', u'Amphinobi'], [u'Sapereau', u'Excavarenne'], [u'Sapereau', u'Excavarenne'], [u'Passerouge', u'Braisillon', u'Flambusard'], [u'Passerouge', u'Braisillon', u'Flambusard'], [u'Passerouge', u'Braisillon', u'Flambusard'], [u'Lepidonille', u'Peregrain', u'Prismillon'], [u'Lepidonille', u'Peregrain', u'Prismillon'], [u'Lepidonille', u'Peregrain', u'Prismillon'], [u'Helionceau', u'Nemelios'], [u'Helionceau', u'Nemelios'], [u'Flabebe', u'Floette', u'Florges'], [u'Flabebe', u'Floette', u'Florges'], [u'Flabebe', u'Floette', u'Florges'], [u'Cabriolaine', u'Chevroum'], [u'Cabriolaine', u'Chevroum'], [u'Pandespiegle', u'Pandarbare'], [u'Pandespiegle', u'Pandarbare'], [], [u'Psystigri', u'Mistigrix'], [u'Psystigri', u'Mistigrix'], [u'Monorpale', u'Dimocles', u'Exagide'], [u'Monorpale', u'Dimocles', u'Exagide'], [u'Monorpale', u'Dimocles', u'Exagide'], [u'Monorpale', u'Dimocles', u'Exagide'], [u'Fluvetin', u'Cocotine'], [u'Fluvetin', u'Cocotine'], [u'Sucroquin', u'Cupcanaille'], [u'Sucroquin', u'Cupcanaille'], [u'Sepiatop', u'Sepiatroce'], [u'Sepiatop', u'Sepiatroce'], [u'Opermine', u'Golgopathe'], [u'Opermine', u'Golgopathe'], [u'Venalgue', u'Kravarech'], [u'Venalgue', u'Kravarech'], [u'Flingouste', u'Gamblast'], [u'Flingouste', u'Gamblast'], [u'Galvaran', u'Iguolta'], [u'Galvaran', u'Iguolta'], [u'Ptyranidur', u'Rexillius'], [u'Ptyranidur', u'Rexillius'], [u'Amagara', u'Dragmara'], [u'Amagara', u'Dragmara'], [u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali'], [], [], [], [u'Mucuscule', u'Colimucus', u'Muplodocus'], [u'Mucuscule', u'Colimucus', u'Muplodocus'], [u'Mucuscule', u'Colimucus', u'Muplodocus'], [], [u'Brocelome', u'Desseliande'], [u'Brocelome', u'Desseliande'], [u'Pitrouille', u'Banshitrouye'], [u'Pitrouille', u'Banshitrouye'], [u'Pitrouille', u'Banshitrouye'], [u'Pitrouille', u'Banshitrouye'], [u'Pitrouille', u'Banshitrouye'], [u'Pitrouille', u'Banshitrouye'], [u'Pitrouille', u'Banshitrouye'], [u'Pitrouille', u'Banshitrouye'], [u'Grelacon', u'Seracrawl'], [u'Grelacon', u'Seracrawl'], [u'Sonistrelle', u'Bruyverne'], [u'Sonistrelle', u'Bruyverne'], [], [], []]

evoList = [(u'Ptitard', u'Tetarte', u'Tartard', u'Tarpaud'), (u'Absol', u'Mega-Absol'), (u'Sapereau', u'Excavarenne'), (u'Kokiyas', u'Crustabri'), (u'Dynavolt', u'Elecsprint', u'Mega-Elecsprint'), (u'Polarhume', u'Polagriffe'), (u'Scorplane', u'Scorvol'), (u'Scarhino', u'Mega-Scarhino'), (u'Loupio', u'Lanturn'), (u'Sancoki', u'Tritosor'), (u'Rhinocorne', u'Rhinoferos', u'Rhinastoc'), (u'Solochi', u'Diamat', u'Trioxhydre'), (u'Ouisticram', u'Chimpenfeu', u'Simiabraz'), (u'Mimitoss', u'Aeromite'), (u'Meditikka', u'Charmina', u'Mega-Charmina'), (u'Aspicot', u'Coconfort', u'Dardargnan'), (u'Anorith', u'Armaldo'), (u'Charpenti', u'Ouvrifier', u'Betochef'), (u'Tutafeh', u'Tutankafer'), (u'Nirondelle', u'Heledelle'), (u'Fouinette', u'Fouinar'), (u'Krabby', u'Krabboss'), (u'Keunotor', u'Castorno'), (u'Ramoloss', u'Flagadoss', u'Roigada'), (u'Mysdibule', u'Mega-Mysdibule'), (u'Griknot', u'Carmache', u'Carchacrok', u'Mega-Carchacrok'), (u'Anchwatt', u'Lamperoie', u'Ohmassacre'), (u'Piafabec', u'Rapasdepic'), (u'Baudrive', u'Grodrive'), (u'Melo', u'Melofee', u'Melodelfe'), (u'Feuillajou', u'Feuiloutan'), (u'Tylton', u'Altaria'), (u'Rapion', u'Drascore'), (u'Amonita', u'Amonistar'), (u'Ceribou', u'Ceriflor'), (u'Tadmorv', u'Grotadmorv'), (u'Carapuce', u'Carabaffe', u'Tortank', u'Mega-Tortank'), (u'Arcko', u'Massko', u'Jungko'), (u'Poussifeu', u'Galifeu', u'Brasegali', u'Mega-Brasegali'), (u'Terhal', u'Metang', u'Metalosse'), (u'Malosse', u'Demolosse', u'Mega-Demolosse'), (u'Flabebe', u'Floette', u'Florges'), (u'Manzai', u'Simularbre'), (u'Chlorobule', u'Fragilady'), (u'Taupiqueur', u'Triopikeur'), (u'Chetiflor', u'Boustiflor', u'Empiflor'), (u'Poichigeon', u'Colombeau', u'Deflaisan'), (u'Snubbull', u'Granbull'), (u'Evoli', u'Aquali', u'Voltali', u'Pyroli', u'Mentali', u'Noctali', u'Phyllali', u'Givrali', u'Nymphali'), (u'Stalgamin', u'Oniglali', u'Momartik'), (u'Grindur', u'Noacier'), (u'Mime Jr.', u'M. Mime'), (u'Gruikui', u'Grotichon', u'Roitiflam'), (u'Machoc', u'Machopeur', u'Mackogneur'), (u'Flamajou', u'Flamoutan'), (u'Cradopaud', u'Coatox'), (u'Polichombr', u'Branette', u'Mega-Branette'), (u'Tritonde', u'Batracne', u'Crapustule'), (u'Debugant', u'Kicklee', u'Tygnon', u'Kapoera'), (u'Tortipouss', u'Boskara', u'Torterra'), (u'Kaiminus', u'Crocrodil', u'Aligatueur'), (u'Draby', u'Drackhaus', u'Drattak'), (u'Soporifik', u'Hypnomade'), (u'Korillon', u'Eoko'), (u'Medhyena', u'Grahyena'), (u'Kangourex', u'Mega-Kangourex'), (u'Ptiravi', u'Leveinard', u'Leuphorie'), (u'Lepidonille', u'Peregrain', u'Prismillon'), (u'Hypotrempe', u'Hypocean', u'Hyporoi'), (u'Barloche', u'Barbicha'), (u'Grainipiot', u'Pifeuil', u'Tengalice'), (u'Toudoudou', u'Rondoudou', u'Grodoudou'), (u'Galvaran', u'Iguolta'), (u'Cacnea', u'Cacturne'), (u'Barpau', u'Milobellus'), (u'Feunnec', u'Roussil', u'Goupelin'), (u'Chovsourir', u'Rhinolove'), (u'Axoloto', u'Maraiste'), (u'Cheniti', u'Cheniselle', u'Papilord'), (u'Chenipotte', u'Armulys', u'Blindalys', u'Charmillon', u'Papinox'), (u'Opermine', u'Golgopathe'), (u'Sonistrelle', u'Bruyverne'), (u'Arakdo', u'Maskadra'), (u'Balignon', u'Chapignon'), (u'Gobou', u'Flobio', u'Laggron'), (u'Nucleos', u'Meios', u'Symbios200e'), (u'Brocelome', u'Desseliande'), (u'Abo', u'Arbok'), (u'Crikzik', u'Melokrik'), (u'Kranidos', u'Charkos'), (u'Feuforeve', u'Magireve'), (u'Nosferapti', u'Nosferalto', u'Nostenfer'), (u'Germignon', u'Macronium', u'Meganium'), (u'Escargaume', u'Limaspeed'), (u'Gringolem', u'Golemastoc'), (u'Hericendre', u'Feurisson', u'Typhlosion'), (u'Crabicoque', u'Crabaraque'), (u'Scalpion', u'Scalproie'), (u'Kabuto', u'Kabutops'), (u'Voltorbe', u'Electrode'), (u'Racaillou', u'Gravalanch', u'Grolem'), (u'Blizzi', u'Blizzaroi', u'Mega-Blizzaroi'), (u'Natu', u'Xatu'), (u'Grelacon', u'Seracrawl'), (u'Rattata', u'Rattatac'), (u'Grenousse', u'Croaporal', u'Amphinobi'), (u'Makuhita', u'Hariyama'), (u'Ponchiot', u'Ponchien', u'Mastouffe'), (u'Capumain', u'Capidextre'), (u'Otaria', u'Lamantine'), (u'Pandespiegle', u'Pandarbare'), (u'Teddiursa', u'Ursaring'), (u'Marisson', u'Boguerisse', u'Blindepique'), (u'Azurill', u'Marill', u'Azumarill'), (u'Bulbizarre', u'Herbizarre', u'Florizarre', u'Mega-Florizarre'), (u'Togepi', u'Togetic', u'Togekiss'), (u'Parecool', u'Vigoroth', u'Monaflemit'), (u'Cornebre', u'Corboss'), (u'Chaglam', u'Chaffreux'), (u'Viskuse', u'Moyade'), (u'Pomdepik', u'Foretress'), (u'Magby', u'Magmar', u'Maganon'), (u'Kraknoix', u'Vibraninf', u'Libegon'), (u'Scrutella', u'Mesmerella', u'Siderella'), (u'Remoraid', u'Octillery'), (u'Poissirene', u'Poissoroy'), (u'Munna', u'Mushana'), (u'Roucool', u'Roucoups', u'Roucarnage'), (u'Arkeapti', u'Aeropteryx'), (u'Larveyette', u'Couverdure', u'Manternel'), (u'Miaouss', u'Persian'), (u'Coquiperl', u'Serpang', u'Rosabyss'), (u'Ningale', u'Ninjask', u'Munja'), (u'Archeomire', u'Archeodong'), (u'Chacripan', u'Leopardus'), (u'Sorbebe', u'Sorboul', u'Sorbouboul'), (u'Pichu', u'Pikachu', u'Raichu'), (u'Doduo', u'Dodrio'), (u'Pitrouille', u'Banshitrouye'), (u'Mustebouee', u'Musteflott'), (u'Lewsor', u'Neitram'), (u'Chenipan', u'Chrysacier', u'Papilusion'), (u'Moustillon', u'Mateloutre', u'Clamiral'), (u'Psykokwak', u'Akwakwak'), (u'Funecire', u'Melancolux', u'Lugulabre'), (u'Statitik', u'Mygavolt'), (u'Hippopotas', u'Hippodocus'), (u'Wailmer', u'Wailord'), (u'Scarabrute', u'Mega-Scarabrute'), (u'Etourmi', u'Etourvol', u'Etouraptor'), (u'Skitty', u'Delcatty'), (u'Marcacrin', u'Cochignon', u'Mammochon'), (u'Trompignon', u'Gaulet'), (u'Rototaupe', u'Minotaupe'), (u'Limagma', u'Volcaropod'), (u'Ponyta', u'Galopa'), (u'Spoink', u'Groret'), (u'Okeoke', u'Qulbutoke'), (u'Furaiglon', u'Gueriaigle'), (u'Sabelette', u'Sablaireau'), (u'Vostourno', u'Vaututrice'), (u'Balbuto', u'Kaorine'), (u'Noeunoeuf', u'Noadkoko'), (u'Darumarond', u'Darumacho'), (u'Smogo', u'Smogogo'), (u'Caninos', u'Arcanin'), (u'Ferosinge', u'Colossinge'), (u'Ecayon', u'Lumineon'), (u'Onix', u'Steelix'), (u'Skelenox', u'Teraclope', u'Noctunoir'), (u'Amagara', u'Dragmara'), (u'Saquedeneu', u'Bouldeneu'), (u'Tic', u'Clic', u'Cliticlic'), (u'Venalgue', u'Kravarech'), (u'Chuchmur', u'Ramboum', u'Brouhabam'), (u'Fantominus', u'Spectrum', u'Ectoplasma', u'Mega-Ectoplasma'), (u'Salameche', u'Reptincel', u'Dracaufeu', u'Mega-Dracaufeu X', u'Mega-Dracaufeu Y'), (u'Mystherbe', u'Ortide', u'Rafflesia', u'Joliflor'), (u'Gloupti', u'Avaltout'), (u'Elekid', u'Elektek', u'Elekable'), (u'Vipelierre', u'Lianaja', u'Majaspic'), (u'Insecateur', u'Cizayox', u'Mega-Cizayox'), (u'Obalie', u'Phogleur', u'Kaimorse'), (u'Ecrapince', u'Colhomard'), (u'Minidraco', u'Draco', u'Dracolosse'), (u'Magicarpe', u'Leviator', u'Mega-Leviator'), (u'Carabing', u'Lancargot'), (u'Miamiasme', u'Miasmax'), (u'Venipatte', u'Scobolide', u'Brutapode'), (u'Tarinor', u'Tarinorme'), (u'Farfuret', u'Dimoret'), (u'Pyronille', u'Pyrax'), (u'Goinfrex', u'Ronflex'), (u'Nidoran M', u'Nidorino', u'Nidoking'), (u'Sepiatop', u'Sepiatroce'), (u'Baggiguane', u'Baggaid'), (u'Mimigal', u'Migalos'), (u'Mascaiman', u'Escroco', u'Crocorible'), (), (u'Apitrini', u'Apireine'), (u'Ptera', u'Mega-Ptera'), (u'Couaneton', u'Lakmecygne'), (u'Nucleos', u'Meios'), (u'Coupenotte', u'Incisache', u'Tranchodon'), (u'Fluvetin', u'Cocotine'), (u'Kungfouine', u'Shaofouine'), (u'Doudouvet', u'Farfaduvet'), (u'Flingouste', u'Gamblast'), (u'Sucroquin', u'Cupcanaille'), (u'Dinoclier', u'Bastiodon'), (u'Riolu', u'Lucario', u'Mega-Lucario'), (u'Porygon', u'Porygon2', u'Porygon-Z'), (u'Tournegrin', u'Heliatronc'), (u'Passerouge', u'Braisillon', u'Flambusard'), (u'Laporeille', u'Lockpin'), (u'Moufouette', u'Moufflair'), (u'Zorua', u'Zoroark'), (u'Excelangue', u'Coudlangue'), (u'Monorpale', u'Dimocles', u'Exagide'), (u'Nenupiot', u'Lombre', u'Ludicolo'), (u'Chinchidou', u'Pashmilla'), (u'Lilia', u'Vacilys'), (u'Lixy', u'Luxio', u'Luxray'), (u'Carapagos', u'Megapagos'), (u'Tiplouf', u'Prinplouf', u'Pingoleon'), (u'Nodulithe', u'Geolithe', u'Gigalithe'), (u'Zigzaton', u'Lineon'), (u'Carvanha', u'Sharpedo'), (u'Tentacool', u'Tentacruel'), (u'Mewtwo', u'Mega-Mewtwo X', u'Mega-Mewtwo Y'), (u'Babimanta', u'Demanta'), (u'Osselait', u'Ossatueur'), (u'Ptyranidur', u'Rexillius'), (u'Phanpy', u'Donphan'), (u'Tarsal', u'Kirlia', u'Gardevoir', u'Gallame', u'Mega-Gardevoir'), (u'Embrylex', u'Ymphect', u'Tyranocif', u'Mega-Tyranocif'), (u'Mucuscule', u'Colimucus', u'Muplodocus'), (u'Ratentif', u'Miradar'), (u'Wattouat', u'Lainergie', u'Pharamp', u'Mega-Pharamp'), (u'Yanma', u'Yanmega'), (u'Paras', u'Parasect'), (u'Goupix', u'Feunard'), (u'Abra', u'Kadabra', u'Alakazam', u'Mega-Alakazam'), (u'Chamallot', u'Camerupt'), (u'Hoot-hoot', u'Noarfang'), (u'Goelise', u'Bekipan'), (u'Galekid', u'Galegon', u'Galeking', u'Mega-Galeking'), (u'Lippouti', u'Lippoutou'), (u'Rozbouton', u'Roselia', u'Roserade'), (u'Magneti', u'Magneton', u'Magnezone'), (u'Granivol', u'Floravol', u'Cotovol'), (u'Coxy', u'Coxyclaque'), (u'Zebibron', u'Zeblitz'), (u'Helionceau', u'Nemelios'), (u'Vivaldaim', u'Haydaim'), (u'Flotajou', u'Flotoutan'), (u'Psystigri', u'Mistigrix'), (u'Cabriolaine', u'Chevroum'), (u'Nidoran F', u'Nidorina', u'Nidoqueen')]
pkList = ['Rattatac', 'Porygon-Z', 'Baggiguane', 'Noadkoko', 'Gueriaigle', 'Polichombr', 'Gaulet', 'Hyporoi', 'Elekable', 'Roussil', 'Pashmilla', 'Emolga', 'Grolem', 'Cresselia', 'Flotoutan', 'Bekipan', 'Mateloutre', 'Dinoclier', 'Absol', 'Azurill', 'Apireine', 'Dracaufeu', 'Solochi', 'Motisma (Forme Tonte)', 'Volcaropod', 'Boreas (Forme Totemique)', 'Meloetta (Forme Voix)', 'Snubbull', 'Sharpedo', 'Motisma (Forme Froid)', 'Mega-Mewtwo Y', 'Tutafeh', 'Noctunoir', 'Melodelfe', 'Mega-Mewtwo X', 'Celebi', 'Cocotine', 'Zorua', 'Mega-Elecsprint', 'Carabing', 'Okeoke', 'Hypotrempe', 'Nymphali', 'Venalgue', 'Mega-Scarabrute', 'Maraiste', 'Mega-Florizarre', 'Papilusion', 'Charpenti', 'Doduo', 'Coatox', 'Charmina', 'Voltali', 'Pitrouille (Taille Maxi)', 'Cheniselle (Cape Dechet)', 'Exagide (Forme Assaut)', 'Joliflor', 'Tarsal', 'Scalpion', 'Galegon', 'Smogogo', 'Baudrive', 'Libegon', 'Pomdepik', 'Korillon', 'Boguerisse', 'Mime Jr.', 'Queulorior', 'Ecremeuh', 'Lineon', 'Osselait', 'Castorno', 'Hypnomade', 'Lilia', 'Motisma (Forme Helice)', 'Kranidos', 'Mammochon', 'Moufouette', 'Miasmax', 'Aflamanoir', 'Makuhita', 'Cerfrousse', 'Alakazam', 'Mega-Dracaufeu X', 'Reptincel', 'Carapagos', 'Hypocean', 'Tortipouss', 'Stalgamin', 'Lancargot', 'Chuchmur', 'Motisma (Forme Normale)', 'Maganon', 'Parecool', 'Wattouat', 'Opermine', 'Prinplouf', 'Anchwatt', 'Posipi', 'Exagide (Forme Parade)', 'Elekid', 'Flambusard', 'Balbuto', 'Yanma', 'Poichigeon', 'Lamperoie', 'Kirlia', 'Couaneton', 'Mystherbe', 'Metang', 'Tritosor', 'Dracolosse', 'Fragilady', 'Genesect', 'Nidorino', 'Branette', 'Nidorina', 'Rhinoferos', 'Regigigas', 'Tentacruel', 'Chlorobule', 'Darumacho (Mode Daruma)', 'Ferosinge', 'Flagadoss', 'Crikzik', 'Florges', 'Scarabrute', 'Mimigal', 'Dodrio', 'Pijako', 'Lepidonille', 'Bargantua', 'Chrysacier', 'Electrode', 'Sorbebe', 'Givrali', 'Gloupti', 'Gringolem', 'Miamiasme', 'Togepi', 'Corboss', 'Flamajou', 'Etourvol', 'Abo', 'Obalie', 'Octillery', 'Feuillajou', 'Zygarde', 'Pikachu', 'Zoroark', 'Mega-Mysdibule', 'Nodulithe', 'Rhinastoc', 'Mega-Gardevoir', 'Mega-Brasegali', 'Grainipiot', 'Qwilfish', 'Carchacrok', 'Latios', 'Groret', 'Cheniselle (Cape Plante)', 'Oniglali', 'Steelix', 'Crefollet', 'Electhor', 'Phanpy', 'Crehelf', 'Ortide', 'Metalosse', 'Azumarill', 'Kyogre', 'Mega-Branette', 'Scorplane', 'Chenipotte', 'Elektek', 'Vigoroth', 'Leveinard', 'Fouinar', 'Simularbre', 'Polagriffe', 'Maracachi', 'Dragmara', 'Insecateur', 'Laporeille', 'Hoot-hoot', 'Lokhlass', 'Spiritomb', 'Limagma', 'Paras', 'Pyronille', 'Symbios', 'Melo', 'Lianaja', 'Arcko', 'Archeomire', 'Banshitrouye (Taille Normale)', 'Feuforeve', 'Mega-Tortank', 'Venipatte', 'Doudouvet', 'Lamantine', 'Parasect', 'Avaltout', 'Voltorbe', 'Magicarpe', 'Darumacho (Mode Normal)', 'Heledelle', 'Noacier', 'Laggron', 'Gobou', 'Canarticho', 'Groudon', 'Blizzaroi', 'Tournegrin', 'Nidoqueen', 'Altaria', 'Roucool', 'Cradopaud', 'Malosse', 'Vaututrice', 'Togekiss', 'Tritonde', 'Moufflair', 'Tiplouf', 'Lumivole', 'Carmache', 'Cliticlic', 'Giratina (Forme Originelle)', 'Poussifeu', 'Limaspeed', 'Iguolta', 'Cheniti', 'Kapoera', 'Pachirisu', 'Marill', 'Mega-Lucario', 'Skitty', 'Abra', 'Couverdure', 'Grodoudou', 'Ptyranidur', 'Kecleon', 'Deoxys (Forme Vitesse)', 'Crustabri', 'Motisma (Forme Chaleur)', 'Galvaran', 'Fluvetin', 'Haydaim', 'Kyurem (Noir)', 'Hippopotas', 'Giratina (Forme Alternative)', 'Coconfort', 'Noeunoeuf', 'Zigzaton', 'Rattata', 'Girafarig', 'Otaria', 'Granbull', 'Kabutops', 'Ratentif', 'Cheniselle (Cape Sol)', 'Bulbizarre', 'Couafarel', 'Mega-Demolosse', 'Siderella', 'Dedenne', 'Herbizarre', 'Lixy', 'Roucarnage', 'Tarinor', 'Rapasdepic', 'Embrylex', 'Togetic', 'Mega-Galeking', 'Brouhabam', 'Babimanta', 'Rhinolove', 'Florizarre', 'Clamiral', 'Ronflex', 'Kyurem (Blanc)', 'Grotadmorv', 'Ptitard', 'Mentali', 'Betochef', 'Stari', 'Arkeapti', 'Crocorible', 'Heatran', 'Ponyta', 'Crefadet', 'Escroco', 'Hariyama', 'Qulbutoke', 'Staross', 'Hexagel', 'Lippouti', 'Bastiodon', 'Peregrain', 'Carvanha', 'Pharamp', 'Mega-Charmina', 'Bouldeneu', 'Heliatronc', 'Gamblast', 'Eoko', 'Brutalibre', 'Furaiglon', 'Chevroum', 'Flamoutan', 'Prismillon', 'Sonistrelle', 'Goupix', 'Gravalanch', 'Nostenfer', 'Chetiflor', 'Motisma (Forme Lavage)', 'Lumineon', 'Croaporal', 'Rhinocorne', 'Leviator', 'Cryptero', 'Spoink', 'Dialga', 'Sabelette', 'Dynavolt', 'Pichu', 'Terrakium', 'Amagara', 'Poissirene', 'Magby', 'Farfaduvet', 'Lockpin', 'Loupio', 'Elecsprint', 'Banshitrouye (Taille Ultra)', 'Keldeo', 'Jungko', 'Boreas (Forme Avatar)', 'Registeel', 'Xatu', 'Skelenox', 'Etourmi', 'Aeromite', 'Tortank', 'Mega-Cizayox', 'Minidraco', 'Trioxhydre', 'Melofee', 'Crabicoque', 'Torterra', 'Rototaupe', 'Ceribou', 'Keunotor', 'Nidoran F', 'Helionceau', 'Entei', 'Nidoran M', 'Moustillon', 'Mygavolt', 'Soporifik', 'Dimocles', 'Riolu', 'Aspicot', 'Marcacrin', 'Mysdibule', 'Chartor', 'Minotaupe', 'Maskadra', 'Yanmega', 'Melokrik', 'Scobolide', 'Massko', 'Brasegali', 'Sepiatroce', 'Vostourno', 'Ossatueur', 'Cabriolaine', 'Lombre', 'Apitrini', 'Nirondelle', 'Chinchidou', 'Arceus', 'Mega-Ptera', 'Kadabra', 'Regirock', 'Deoxys (Forme Attaque)', 'Tarpaud', 'Sapereau', 'Cacturne', 'Raichu', 'Poissoroy', 'Vibraninf', 'Vacilys', 'Vivaldaim', 'Tadmorv', 'Zarbi', 'Galifeu', 'Dardargnan', 'Polarhume', 'Tylton', 'Roitiflam', 'Manternel', 'Cornebre', 'Terhal', 'Shaofouine', 'Papilord', 'Fantominus', 'Lakmecygne', 'Kraknoix', 'Leuphorie', 'Boskara', 'Charkos', 'Gigalithe', 'Roucoups', 'Ecayon', 'Statitik', 'Teraclope', 'Aquali', 'Geolithe', 'Draco', 'Magnezone', 'Roselia', 'Monaflemit', 'Spinda', 'Tartard', 'Palkia', 'Darumarond', 'Munna', 'Tauros', 'Etouraptor', 'Frison', 'Raikou', 'Pingoleon', 'Hericendre', 'Arbok', 'Mesmerella', 'Chimpenfeu', 'Psykokwak', 'Boustiflor', 'Porygon2', 'Kaimorse', 'Akwakwak', 'Tygnon', 'Goinfrex', 'Griknot', 'Sucroquin', 'Escargaume', 'Monorpale', 'Goupelin', 'Tenefix', 'Mustebouee', 'Nosferalto', 'Judokrak', 'Relicanth', 'Mushana', 'Ptiravi', 'Coquiperl', 'Ohmassacre', 'Brocelome', 'Rozbouton', 'Scalproie', 'Phogleur', 'Neitram', 'Chovsourir', 'Musteflott', 'Insolourdo', 'Mega-Tyranocif', 'Munja', 'Drakkarmin', 'Sorbouboul', 'Mega-Blizzaroi', 'Zekrom', 'Remoraid', 'Mamanbo', 'Meios', 'Noctali', 'Mega-Pharamp', 'Ramoloss', 'Cupcanaille', 'Carabaffe', 'Barbicha', 'Colombeau', 'Baggaid', 'Ramboum', 'Kicklee', 'Teddiursa', 'Karaclee', 'Serpang', 'Porygon', 'Mastouffe', 'Pyrax', 'Majaspic', 'Blindalys', 'Nenupiot', 'Foretress', 'Mimitoss', 'Lippoutou', 'Negapi', 'Mega-Leviator', 'Mega-Dracaufeu Y', 'Colimucus', 'Ouisticram', 'Gruikui', 'Gallame', 'Flotajou', 'Pandespiegle', 'Muplodocus', 'Blindepique', 'Melancolux', 'Viridium', 'Fouinette', 'Desseliande', 'Seviper', 'Germignon', 'Ponchiot', 'Typhlosion', 'Demeteros (Forme Avatar)', 'Feunard', 'Magneti', 'Cobaltium', 'Persian', 'Nidoking', 'Ninjask', 'Amphinobi', 'Nemelios', 'Medhyena', 'Evoli', 'Barloche', 'Kabuto', 'Grenousse', 'Kaorine', 'Debugant', 'Ningale', 'Capidextre', 'Tic', 'Piafabec', 'Camerupt', 'Goelise', 'Funecire', 'Golgopathe', 'Reshiram', 'Excelangue', 'Tetarte', 'Mega-Ectoplasma', 'Flingouste', 'Aligatueur', 'Magireve', 'Luxray', 'Rosabyss', 'Galekid', 'Ptera', 'Galopa', 'Roigada', 'Jirachi', 'Pitrouille (Taille Mini)', 'Marisson', 'Mascaiman', 'Carapuce', 'Mangriff', 'Latias', 'Grahyena', 'Lugia', 'Onix', 'Pyroli', 'Magneton', 'Incisache', 'Kokiyas', 'Racaillou', 'Colhomard', 'Papinox', 'Manaphy', 'Crocrodil', 'Ectoplasma', 'Nucleos', 'Vortente', 'Ecrapince', 'Coxyclaque', 'Lugulabre', 'Moyade', 'Delcatty', 'Floette', 'Tutankafer', 'Meditikka', 'Nanmeouie', 'Feunnec', 'Archeodong', 'Axoloto', 'Macronium', 'Rafflesia', 'Caratroc', 'Shaymin (Forme Celeste)', 'Ponchien', 'Pifeuil', 'Toudoudou', 'Sablaireau', 'Banshitrouye (Taille Mini)', 'Draby', 'Rayquaza', 'Granivol', 'Luxio', 'Ceriflor', 'Dimoret', 'Amonita', 'Larveyette', 'Krabboss', 'Batracne', 'Tentacool', 'Hippodocus', 'Wailmer', 'Magmar', 'Caninos', 'Seleroc', 'Lucario', 'Machopeur', 'Barpau', 'Armulys', 'Drascore', 'Coudlangue', 'Tarinorme', 'Lovdisc', 'Saquedeneu', 'Tengalice', 'Golemastoc', 'Diamat', 'Phyllali', 'Mistigrix', 'Grotichon', 'Tropius', 'Salameche', 'Victini', 'Ymphect', 'Artikodin', 'Phione', 'Miaouss', 'Braisillon', 'Migalos', 'Manzai', 'Nosferapti', 'Arakdo', 'Kaiminus', 'Charmillon', 'Zebibron', 'Coupenotte', 'Muciole', 'Cizayox', 'Triopikeur', 'Floravol', 'Ouvrifier', 'Darkrai', 'Mew', 'Grindur', 'Balignon', 'Kravarech', 'Chaglam', 'Xerneas', 'Cadoizo', 'Mega-Kangourex', 'Chapignon', 'Lanturn', 'Simiabraz', 'Bruyverne', 'Mucuscule', 'Chaffreux', 'Aeropteryx', 'Farfuret', 'Cotovol', 'Rondoudou', 'Sorboul', 'Amonistar', 'Clic', 'Meganium', 'Deoxys (Forme Defense)', 'Viskuse', 'Metamorph', 'Kangourex', 'Pitrouille (Taille Normale)', 'Wailord', 'Colossinge', 'Yveltal', 'Fulguris (Forme Totemique)', 'Corayon', 'Mackogneur', 'Rapion', 'Feuiloutan', 'Ursaring', 'Anorith', 'Vipelierre', 'Gardevoir', 'Scarhino', 'Demolosse', 'Crapustule', 'Crabaraque', 'Tranchodon', 'Mewtwo', 'Feurisson', 'Galeking', 'Miradar', 'Tyranocif', 'Scorvol', 'Demanta', 'Solaroc', 'Passerouge', 'Mega-Scarhino', 'Flobio', 'Cochignon', 'Roserade', 'Chamallot', 'Chacripan', 'Psystigri', 'Scrutella', 'Kungfouine', 'Momartik', 'Leopardus', 'Ho-Oh', 'Krabby', 'Suicune', 'Zeblitz', 'Excavarenne', 'Donphan', 'Grelacon', 'Pitrouille (Taille Ultra)', 'Blizzi', 'Mega-Absol', 'Strassie', 'Trousselin', 'Morpheo', 'Airmure', 'M. Mime', 'Natu', 'Lainergie', 'Mega-Carchacrok', 'Coxy', 'Shaymin (Forme Terrestre)', 'Banshitrouye (Taille Maxi)', 'Cacnea', 'Smogo', 'Arcanin', 'Milobellus', 'Taupiqueur', 'Capumain', 'Fulguris (Forme Avatar)', 'Machoc', 'Ludicolo', 'Noarfang', 'Meloetta (Forme Danse)', 'Sepiatop', 'Fermite', 'Regice', 'Armaldo', 'Lewsor', 'Sancoki', 'Demeteros (Forme Totemique)', 'Trompignon', 'Empiflor', 'Drackhaus', 'Chenipan', 'Limonde', 'Grodrive', 'Flabebe', 'Mega-Alakazam', 'Brutapode', 'Deoxys (Forme de Base)', 'Megapagos', 'Deflaisan', 'Spectrum', 'Pandarbare', 'Rexillius', 'Sulfura', 'Drattak', 'Seracrawl']
main(pkList, evoList)
